# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain_os/common/types.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'brain_os/common/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x62rain_os/common/types.proto\x12\x0f\x62rain_os.common\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"d\n\x04Pose\x12*\n\x08position\x18\x01 \x01(\x0b\x32\x18.brain_os.common.Vector3\x12\x30\n\x0borientation\x18\x02 \x01(\x0b\x32\x1b.brain_os.common.Quaternion\"\\\n\x05Twist\x12(\n\x06linear\x18\x01 \x01(\x0b\x32\x18.brain_os.common.Vector3\x12)\n\x07\x61ngular\x18\x02 \x01(\x0b\x32\x18.brain_os.common.Vector3\"d\n\rBoundingBox3D\x12%\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x15.brain_os.common.Pose\x12,\n\ndimensions\x18\x02 \x01(\x0b\x32\x18.brain_os.common.Vector3\"R\n\x06Header\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12)\n\x05stamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\t\"D\n\x06Status\x12)\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1b.brain_os.common.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"V\n\tRobotInfo\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x11\n\tserial_no\x18\x03 \x01(\t\x12\x10\n\x08\x66irmware\x18\x04 \x01(\t*\xa2\x01\n\nStatusCode\x12\r\n\tSTATUS_OK\x10\x00\x12\x10\n\x0cSTATUS_ERROR\x10\x01\x12\x12\n\x0eSTATUS_TIMEOUT\x10\x02\x12\x14\n\x10STATUS_CANCELLED\x10\x03\x12\x1a\n\x16STATUS_INVALID_REQUEST\x10\x04\x12\x14\n\x10STATUS_NOT_READY\x10\x05\x12\x17\n\x13STATUS_UNAUTHORIZED\x10\x06\x42\x31Z/github.com/brain-os/brain_proto/brain_os/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_os.common.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/brain-os/brain_proto/brain_os/common'
  _globals['_STATUSCODE']._serialized_start=754
  _globals['_STATUSCODE']._serialized_end=916
  _globals['_VECTOR3']._serialized_start=111
  _globals['_VECTOR3']._serialized_end=153
  _globals['_QUATERNION']._serialized_start=155
  _globals['_QUATERNION']._serialized_end=211
  _globals['_POSE']._serialized_start=213
  _globals['_POSE']._serialized_end=313
  _globals['_TWIST']._serialized_start=315
  _globals['_TWIST']._serialized_end=407
  _globals['_BOUNDINGBOX3D']._serialized_start=409
  _globals['_BOUNDINGBOX3D']._serialized_end=509
  _globals['_HEADER']._serialized_start=511
  _globals['_HEADER']._serialized_end=593
  _globals['_STATUS']._serialized_start=595
  _globals['_STATUS']._serialized_end=663
  _globals['_ROBOTINFO']._serialized_start=665
  _globals['_ROBOTINFO']._serialized_end=751
# @@protoc_insertion_point(module_scope)
