server:
  port: 8312

spring:
  application:
    name: qoocommunity-event
  datasource:
    url: jdbc:postgresql://localhost:5432/qoocommunity
    username: qoobot
    password: qoobot123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

rocketmq:
  name-server: localhost:9876
  producer:
    group: qoocommunity-event-producer
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
