# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain_os/decision/types.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'brain_os/decision/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from brain_os.common import types_pb2 as brain__os_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x62rain_os/decision/types.proto\x12\x11\x62rain_os.decision\x1a\x1b\x62rain_os/common/types.proto\"S\n\rJointWaypoint\x12\x11\n\tpositions\x18\x01 \x03(\x01\x12\x12\n\nvelocities\x18\x02 \x03(\x01\x12\x1b\n\x13time_from_start_sec\x18\x03 \x01(\x01\"U\n\x11\x43\x61rtesianWaypoint\x12#\n\x04pose\x18\x01 \x01(\x0b\x32\x15.brain_os.common.Pose\x12\x1b\n\x13time_from_start_sec\x18\x02 \x01(\x01\"\xfb\x01\n\nTrajectory\x12\x15\n\rtrajectory_id\x18\x01 \x01(\t\x12\x10\n\x08robot_id\x18\x02 \x01(\t\x12\x34\n\njoint_path\x18\x03 \x03(\x0b\x32 .brain_os.decision.JointWaypoint\x12<\n\x0e\x63\x61rtesian_path\x18\x04 \x03(\x0b\x32$.brain_os.decision.CartesianWaypoint\x12\r\n\x05score\x18\x05 \x01(\x02\x12\x14\n\x0c\x64uration_sec\x18\x06 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\x12\x16\n\x0eis_recommended\x18\x08 \x01(\x08\"\x89\x01\n\nPlanStatus\x12\x0f\n\x07plan_id\x18\x01 \x01(\t\x12+\n\x05state\x18\x02 \x01(\x0e\x32\x1c.brain_os.decision.PlanState\x12\x10\n\x08progress\x18\x03 \x01(\x02\x12\x14\n\x0c\x63urrent_step\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\"\x7f\n\tHITLEvent\x12\x0f\n\x07plan_id\x18\x01 \x01(\t\x12\x31\n\ncandidates\x18\x02 \x03(\x0b\x32\x1d.brain_os.decision.Trajectory\x12\x13\n\x0btimeout_sec\x18\x03 \x01(\x02\x12\x19\n\x11recommended_index\x18\x04 \x01(\r*\x91\x01\n\tPlanState\x12\r\n\tPLAN_IDLE\x10\x00\x12\x11\n\rPLAN_PLANNING\x10\x01\x12\x15\n\x11PLAN_WAITING_HITL\x10\x02\x12\x12\n\x0ePLAN_EXECUTING\x10\x03\x12\x12\n\x0ePLAN_SUCCEEDED\x10\x04\x12\x0f\n\x0bPLAN_FAILED\x10\x05\x12\x12\n\x0ePLAN_CANCELLED\x10\x06\x42\x33Z1github.com/brain-os/brain_proto/brain_os/decisionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_os.decision.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/brain-os/brain_proto/brain_os/decision'
  _globals['_PLANSTATE']._serialized_start=777
  _globals['_PLANSTATE']._serialized_end=922
  _globals['_JOINTWAYPOINT']._serialized_start=81
  _globals['_JOINTWAYPOINT']._serialized_end=164
  _globals['_CARTESIANWAYPOINT']._serialized_start=166
  _globals['_CARTESIANWAYPOINT']._serialized_end=251
  _globals['_TRAJECTORY']._serialized_start=254
  _globals['_TRAJECTORY']._serialized_end=505
  _globals['_PLANSTATUS']._serialized_start=508
  _globals['_PLANSTATUS']._serialized_end=645
  _globals['_HITLEVENT']._serialized_start=647
  _globals['_HITLEVENT']._serialized_end=774
# @@protoc_insertion_point(module_scope)
