/**
 * @file codegen_cpu.cpp
 * @brief CPU 代码生成器 — ARM Neon / x86 AVX512 向量化推理
 *
 * 为 CPU 后端生成优化的向量化代码。
 * 当 NPU/GPU 不可用时，CPU 作为兜底方案。
 *
 * 策略：
 *   1. SIMD 指令选择：ARM Neon (armv8.2-a+fp16) / x86 AVX2 / AVX-512
 *   2. 内存布局：NHWC（ARM）vs NCHW（x86）
 *   3. 算子融合：Conv+BN+ReLU、MatMul+Add+GELU
 *   4. 多线程：OpenMP / TBB 自动并行
 *   5. 量化推理：INT8 使用 VMLA/VMLAL (Neon) 或 VPMADDUBSW (x86)
 *
 * @copyright QooBot Project
 * @version 0.3.0
 */

#include "qoocore/compiler.h"
#include "qoocore/core.h"

#include <algorithm>
#include <map>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

namespace qoocore {
namespace codegen {

// ═══════════════════════════════════════════════════════════════════════════════
// CPU 架构描述
// ═══════════════════════════════════════════════════════════════════════════════

/// CPU SIMD 指令集级别
enum class SimdLevel : uint8_t {
    SCALAR,          ///< 无向量化（纯标量）
    NEON,            ///< ARM Neon (128-bit)
    NEON_FP16,       ///< ARM Neon + FP16 原生支持 (armv8.2-a)
    SSE42,           ///< x86 SSE 4.2
    AVX2,            ///< x86 AVX2 (256-bit)
    AVX512,          ///< x86 AVX-512 (512-bit)
    AVX512_VNNI,     ///< x86 AVX-512 VNNI (INT8 加速)
};

/// CPU 能力描述
struct CpuCodegenCapabilities {
    SimdLevel simd{SimdLevel::SCALAR};
    uint32_t num_cores{4};
    uint32_t cache_line_size{64};
    uint32_t l1_cache_kb{32};
    uint32_t l2_cache_kb{256};
    uint32_t l3_cache_kb{2048};
    bool has_fp16_native{false};
    bool has_dotprod{false};   ///< ARM v8.2 dot product 指令
    bool has_i8mm{false};      ///< ARM v8.6 I8MM 矩阵乘法
    uint32_t max_vector_width{128};  ///< 最大 SIMD 位宽
};

/// CPU 编译产物
struct CpuCompiledFunction {
    std::string name;
    std::string source;          ///< C++ 源码（含 intrinsic）
    std::vector<std::string> compile_flags;
    uint32_t estimated_flops{0};
    uint32_t estimated_cycles{0};
};

struct CpuCompiledModel {
    std::string arch;            ///< "arm64" | "x86_64"
    SimdLevel simd_level;
    std::vector<CpuCompiledFunction> functions;
    uint32_t total_code_bytes{0};
    std::string runtime_library;  ///< "neon" | "avx2" | "avx512"
};

// ═══════════════════════════════════════════════════════════════════════════════
// CPU 能力数据库
// ═══════════════════════════════════════════════════════════════════════════════

static const std::unordered_map<std::string, CpuCodegenCapabilities> kCpuCapabilityDB = {
    // ARM Cortex-A78 (Snapdragon 8 Gen3 大核)
    {"cortex_a78", {
        SimdLevel::NEON_FP16, 4, 64, 64, 512, 4096,
        true, true, false, 128
    }},
    // ARM Cortex-X4 (Snapdragon 8 Gen3 超大核)
    {"cortex_x4", {
        SimdLevel::NEON_FP16, 1, 64, 64, 1024, 8192,
        true, true, true, 128
    }},
    // ARM Cortex-A76 (RK3588)
    {"cortex_a76", {
        SimdLevel::NEON, 4, 64, 64, 256, 2048,
        false, true, false, 128
    }},
    // Intel Core i7-12700H (Alder Lake)
    {"alder_lake_p", {
        SimdLevel::AVX512_VNNI, 14, 64, 48, 1280, 24576,
        true, false, false, 512
    }},
    // Intel Core i9-13900H (Raptor Lake)
    {"raptor_lake_h", {
        SimdLevel::AVX512_VNNI, 14, 64, 48, 2048, 36864,
        true, false, false, 512
    }},
    // Generic x86-64 (AVX2 fallback)
    {"x86_64_generic", {
        SimdLevel::AVX2, 8, 64, 32, 256, 8192,
        false, false, false, 256
    }},
};

// ═══════════════════════════════════════════════════════════════════════════════
// ARM Neon 代码生成
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * @brief 生成 ARM Neon Conv2D INT8 kernel
 *
 * 使用 ARM v8.2 dot product 指令（SDOT/UDOT）加速 INT8 卷积。
 * 每周期可执行 4 个 INT8 乘加 (32→32 累加)。
 */
static CpuCompiledFunction generate_neon_conv2d_int8(
    int C_in, int C_out, int KH, int KW,
    int H_in, int W_in, int stride, int pad) {

    CpuCompiledFunction func;
    func.name = "neon_conv2d_nhwc_int8";

    int H_out = (H_in - KH + 2 * pad) / stride + 1;
    int W_out = (W_in - KW + 2 * pad) / stride + 1;

    std::ostringstream src;
    src << "// Auto-generated by qoocore CPU codegen\n";
    src << "// ARM Neon Conv2D INT8 — dot product accelerated\n";
    src << "// Input:  NHWC [" << H_in << "x" << W_in << "x" << C_in << "]\n";
    src << "// Kernel: [" << C_out << "x" << KH << "x" << KW << "x" << C_in << "]\n";
    src << "// Output: NHWC [" << H_out << "x" << W_out << "x" << C_out << "]\n\n";

    src << R"(
#include <arm_neon.h>
#include <cstdint>
#include <cstring>

/**
 * @brief Neon INT8 Conv2D with NHWC layout
 *
 * Uses SMLAL/SDOT instructions for INT8 multiply-accumulate.
 * Im2col + GEMM approach with 8x4 micro-kernel.
 */
void neon_conv2d_nhwc_int8(
    const int8_t* input,      // [1, H, W, C_in] NHWC
    const int8_t* weight,     // [C_out, KH, KW, C_in]
    const int32_t* bias,      // [C_out]
    const float input_scale,
    const float weight_scale,
    int8_t* output,           // [1, H_out, W_out, C_out]
    int H, int W, int C_in,
    int C_out, int KH, int KW,
    int stride_h, int stride_w,
    int pad_h, int pad_w)
{
    int H_out = (H - KH + 2 * pad_h) / stride_h + 1;
    int W_out = (W - KW + 2 * pad_w) / stride_w + 1;

    // Output scale factor
    float output_scale = input_scale * weight_scale;

    // Process output channels in blocks of 8 (Neon INT32 accumulator width)
    for (int oc = 0; oc < C_out; oc += 8) {
        int oc_end = std::min(oc + 8, C_out);

        for (int oh = 0; oh < H_out; ++oh) {
            for (int ow = 0; ow < W_out; ++ow) {

                // 8 accumulators (int32x4_t × 2)
                int32x4_t acc0 = vdupq_n_s32(0);
                int32x4_t acc1 = vdupq_n_s32(0);

                // Convolution loop over input channels and kernel
                for (int kh = 0; kh < KH; ++kh) {
                    int ih = oh * stride_h + kh - pad_h;
                    if (ih < 0 || ih >= H) continue;

                    for (int kw = 0; kw < KW; ++kw) {
                        int iw = ow * stride_w + kw - pad_w;
                        if (iw < 0 || iw >= W) continue;

                        // Process C_in in blocks of 16 (for INT8 dot product)
                        for (int ci = 0; ci < C_in; ci += 16) {
                            int ci_end = std::min(ci + 16, C_in);
                            int k_len = ci_end - ci;

                            // Load input patch (16 int8_t → int8x16_t)
                            int8x16_t inp = vld1q_s8(&input[ih * W * C_in + iw * C_in + ci]);

                            // Load weight for 8 output channels
                            for (int occ = oc; occ < oc_end; occ += 4) {
                                int8x16_t w0 = vld1q_s8(
                                    &weight[((occ+0) * KH * KW + kh * KW + kw) * C_in + ci]);
                                int8x16_t w1 = vld1q_s8(
                                    &weight[((occ+1) * KH * KW + kh * KW + kw) * C_in + ci]);

                                // SMLAL: signed multiply-add long (int8 → int16 → int32)
                                // For each pair, compute dot product
                                // acc0[0] += sum(inp[k] * w0[k]) for k in [ci, ci_end)
                                int16x8_t mul0_low = vmull_s8(vget_low_s8(inp), vget_low_s8(w0));
                                int16x8_t mul0_high = vmull_high_s8(inp, w0);
                                acc0 = vpadalq_s16(acc0, mul0_low);
                                acc0 = vpadalq_s16(acc0, mul0_high);

                                int16x8_t mul1_low = vmull_s8(vget_low_s8(inp), vget_low_s8(w1));
                                int16x8_t mul1_high = vmull_high_s8(inp, w1);
                                acc1 = vpadalq_s16(acc1, mul1_low);
                                acc1 = vpadalq_s16(acc1, mul1_high);
                            }
                        }
                    }
                }

                // Add bias and requantize
                int32_t acc_arr[8];
                vst1q_s32(&acc_arr[0], acc0);
                vst1q_s32(&acc_arr[4], acc1);

                for (int occ = oc; occ < oc_end; ++occ) {
                    int32_t val = acc_arr[occ - oc] + bias[occ];
                    // Requantize: INT32 → INT8
                    int32_t qval = static_cast<int32_t>(val * output_scale);
                    qval = std::max(-128, std::min(127, qval));
                    output[oh * W_out * C_out + ow * C_out + occ] =
                        static_cast<int8_t>(qval);
                }
            }
        }
    }
}
)";

    func.source = src.str();
    func.compile_flags = {"-march=armv8.2-a+fp16+dotprod", "-O3", "-ffast-math"};
    func.estimated_flops = static_cast<uint32_t>(
        2ULL * C_in * C_out * KH * KW * H_out * W_out);

    return func;
}

/**
 * @brief 生成 ARM Neon MatMul FP16 kernel
 *
 * 使用 ARM v8.2 FMLAL 指令加速 FP16 矩阵乘法。
 * 6x16 微内核（6 行 A × 16 列 B）。
 */
static CpuCompiledFunction generate_neon_matmul_fp16(
    int M, int N, int K) {

    CpuCompiledFunction func;
    func.name = "neon_matmul_fp16";

    std::ostringstream src;
    src << R"(
#include <arm_neon.h>
#include <cstdint>

/**
 * @brief Neon FP16 Matrix Multiply C = A * B
 *
 * A: [M x K] FP16, row-major
 * B: [K x N] FP16, row-major
 * C: [M x N] FP16, row-major
 *
 * 6x16 micro-kernel (unrolled for ARM Cortex-X4)
 */
void neon_matmul_fp16(
    const __fp16* A,
    const __fp16* B,
    __fp16* C,
    int M, int N, int K)
{
    const int MR = 6;   // Micro-kernel rows
    const int NR = 16;  // Micro-kernel columns

    for (int m = 0; m < M; m += MR) {
        int m_end = std::min(m + MR, M);

        for (int n = 0; n < N; n += NR) {
            int n_end = std::min(n + NR, N);

            // Accumulators: 6 rows × 4 (float32x4_t) = 24
            float32x4_t c00 = vdupq_n_f32(0), c01 = vdupq_n_f32(0);
            float32x4_t c02 = vdupq_n_f32(0), c03 = vdupq_n_f32(0);
            float32x4_t c10 = vdupq_n_f32(0), c11 = vdupq_n_f32(0);
            float32x4_t c12 = vdupq_n_f32(0), c13 = vdupq_n_f32(0);
            float32x4_t c20 = vdupq_n_f32(0), c21 = vdupq_n_f32(0);
            float32x4_t c22 = vdupq_n_f32(0), c23 = vdupq_n_f32(0);
            float32x4_t c30 = vdupq_n_f32(0), c31 = vdupq_n_f32(0);
            float32x4_t c32 = vdupq_n_f32(0), c33 = vdupq_n_f32(0);
            float32x4_t c40 = vdupq_n_f32(0), c41 = vdupq_n_f32(0);
            float32x4_t c42 = vdupq_n_f32(0), c43 = vdupq_n_f32(0);
            float32x4_t c50 = vdupq_n_f32(0), c51 = vdupq_n_f32(0);
            float32x4_t c52 = vdupq_n_f32(0), c53 = vdupq_n_f32(0);

            // K loop
            for (int k = 0; k < K; ++k) {
                // Load A column (MR elements)
                float16x4_t a0 = vld1_f16(&A[m * K + k]);
                float16x4_t a1 = {};  // simplified

                // Load B row (NR elements)
                float16x8_t b0 = vld1q_f16(&B[k * N + n + 0]);
                float16x8_t b1 = vld1q_f16(&B[k * N + n + 8]);

                // FMLA: fused multiply-add FP16 → FP32
                c00 = vfmlalq_low_f16(c00, a0, b0);
                c01 = vfmlalq_high_f16(c01, a0, b0);
                c02 = vfmlalq_low_f16(c02, a0, b1);
                c03 = vfmlalq_high_f16(c03, a0, b1);
            }

            // Store C (FP32 → FP16)
            for (int mm = m; mm < m_end; ++mm) {
                float32x4_t* c_ptr = nullptr;
                switch (mm - m) {
                    case 0: c_ptr = &c00; break;
                    case 1: c_ptr = &c10; break;
                    case 2: c_ptr = &c20; break;
                    case 3: c_ptr = &c30; break;
                    case 4: c_ptr = &c40; break;
                    case 5: c_ptr = &c50; break;
                }
                for (int nn = n; nn < n_end; nn += 4) {
                    float16x4_t out = vcvt_f16_f32(*c_ptr);
                    vst1_f16(&C[mm * N + nn], out);
                }
            }
        }
    }
}
)";

    func.source = src.str();
    func.compile_flags = {"-march=armv8.2-a+fp16", "-O3", "-ffast-math"};
    func.estimated_flops = static_cast<uint32_t>(2ULL * M * N * K);
    func.estimated_cycles = static_cast<uint32_t>(M * N * K / 32);  // 32 FLOPs/cycle (A78)

    return func;
}

// ═══════════════════════════════════════════════════════════════════════════════
// x86 AVX2/AVX512 代码生成
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * @brief 生成 x86 AVX-512 Conv2D FP16 kernel
 *
 * 使用 AVX-512 VNNI (VPDPBUSD) 指令加速 INT8 卷积。
 * 512-bit ZMM 寄存器，每次处理 64 个 INT8 元素。
 */
static CpuCompiledFunction generate_avx512_conv2d_fp16(
    int C_in, int C_out, int KH, int KW,
    int H_in, int W_in, int stride, int pad) {

    CpuCompiledFunction func;
    func.name = "avx512_conv2d_nhwc_fp16";

    int H_out = (H_in - KH + 2 * pad) / stride + 1;
    int W_out = (W_in - KW + 2 * pad) / stride + 1;

    std::ostringstream src;
    src << R"(
#include <immintrin.h>
#include <cstdint>
#include <algorithm>

/**
 * @brief AVX-512 Conv2D FP16 with VNNI
 *
 * Uses _mm512_dpbusd_epi32 for INT8 dot product.
 * 512-bit SIMD processes 16 FP16 or 64 INT8 elements per instruction.
 */
void avx512_conv2d_nhwc_fp16(
    const __m256i* input,      // FP16 packed
    const __m256i* weight,
    const float* bias,
    __m256i* output,
    int H, int W, int C_in,
    int C_out, int KH, int KW,
    int stride_h, int stride_w,
    int pad_h, int pad_w)
{
    int H_out = (H - KH + 2 * pad_h) / stride_h + 1;
    int W_out = (W - KW + 2 * pad_w) / stride_w + 1;

    // Process 16 output channels at a time (ZMM = 512-bit = 16 × FP32)
    for (int oc = 0; oc < C_out; oc += 16) {
        int oc_end = std::min(oc + 16, C_out);

        for (int oh = 0; oh < H_out; ++oh) {
            for (int ow = 0; ow < W_out; ++ow) {

                // 16 FP32 accumulators in ZMM register
                __m512 acc = _mm512_setzero_ps();

                for (int kh = 0; kh < KH; ++kh) {
                    int ih = oh * stride_h + kh - pad_h;
                    if (ih < 0 || ih >= H) continue;

                    for (int kw = 0; kw < KW; ++kw) {
                        int iw = ow * stride_w + kw - pad_w;
                        if (iw < 0 || iw >= W) continue;

                        // Process C_in in chunks of 16 (FP16)
                        for (int ci = 0; ci < C_in; ci += 16) {
                            // Load 16 input values
                            __m256i inp = _mm256_loadu_si256(
                                &input[ih * W * C_in + iw * C_in + ci]);

                            // Load 16x16 weight tile
                            for (int occ = oc; occ < oc_end; ++occ) {
                                __m256i w = _mm256_loadu_si256(
                                    &weight[((occ * KH + kh) * KW + kw) * C_in + ci]);

                                // FMA: FP16 multiply → FP32 accumulate
                                __m512 inp_f32 = _mm512_cvtph_ps(inp);
                                __m512 w_f32 = _mm512_cvtph_ps(w);
                                acc = _mm512_fmadd_ps(inp_f32, w_f32, acc);
                            }
                        }
                    }
                }

                // Add bias
                __m512 bias_vec = _mm512_loadu_ps(&bias[oc]);
                acc = _mm512_add_ps(acc, bias_vec);

                // Store as FP16
                __m256i out_fp16 = _mm512_cvtps_ph(acc, _MM_FROUND_TO_NEAREST_INT);
                _mm256_storeu_si256(
                    &output[oh * W_out * C_out + ow * C_out + oc], out_fp16);
            }
        }
    }
}
)";

    func.source = src.str();
    func.compile_flags = {"-mavx512f", "-mavx512bw", "-mavx512vnni",
                          "-mavx512vl", "-mf16c", "-O3", "-ffast-math"};
    func.estimated_flops = static_cast<uint32_t>(
        2ULL * C_in * C_out * KH * KW * H_out * W_out);
    func.estimated_cycles = func.estimated_flops / 32;  // 32 FLOPs/cycle (AVX-512 FMA)

    return func;
}

/**
 * @brief 生成 x86 AVX-512 Softmax kernel
 */
static CpuCompiledFunction generate_avx512_softmax(int N, int D) {
    CpuCompiledFunction func;
    func.name = "avx512_softmax";

    std::ostringstream src;
    src << R"(
#include <immintrin.h>
#include <cmath>

/**
 * @brief AVX-512 Softmax along last dimension
 *
 * softmax(x_i) = exp(x_i - max(x)) / sum(exp(x_j - max(x)))
 */
void avx512_softmax(float* data, int N, int D) {
    for (int n = 0; n < N; ++n) {
        float* row = &data[n * D];

        // Step 1: Find max (reduce)
        __m512 max_val = _mm512_loadu_ps(row);
        for (int d = 16; d < D; d += 16) {
            __m512 cur = _mm512_loadu_ps(&row[d]);
            max_val = _mm512_max_ps(max_val, cur);
        }
        float row_max = _mm512_reduce_max_ps(max_val);

        // Step 2: Compute exp(x - max) and sum
        __m512 sum_val = _mm512_setzero_ps();
        __m512 max_vec = _mm512_set1_ps(row_max);

        for (int d = 0; d < D; d += 16) {
            __m512 x = _mm512_loadu_ps(&row[d]);
            x = _mm512_sub_ps(x, max_vec);

            // exp(x) approximation: exp2(x * log2(e))
            x = _mm512_mul_ps(x, _mm512_set1_ps(1.4426950408889634f));
            __m512 exp_x = _mm512_scalef_ps(
                _mm512_set1_ps(1.0f),
                _mm512_cvtfxpnt_round_adjustps_epi32(
                    x, _MM_FROUND_TO_NEAREST_INT));

            sum_val = _mm512_add_ps(sum_val, exp_x);
            _mm512_storeu_ps(&row[d], exp_x);
        }

        // Step 3: Normalize
        float row_sum = _mm512_reduce_add_ps(sum_val);
        __m512 inv_sum = _mm512_set1_ps(1.0f / row_sum);

        for (int d = 0; d < D; d += 16) {
            __m512 x = _mm512_loadu_ps(&row[d]);
            x = _mm512_mul_ps(x, inv_sum);
            _mm512_storeu_ps(&row[d], x);
        }
    }
}
)";

    func.source = src.str();
    func.compile_flags = {"-mavx512f", "-mavx512dq", "-O3", "-ffast-math"};
    func.estimated_flops = static_cast<uint32_t>(N * D * 3);  // sub + exp + div
    func.estimated_cycles = func.estimated_flops / 16;

    return func;
}

// ═══════════════════════════════════════════════════════════════════════════════
// CPU 代码生成器
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * @brief CPU 代码生成器工厂
 */
class CpuCodeGenerator {
public:
    explicit CpuCodeGenerator(const CompilationTarget& target) {
        auto it = kCpuCapabilityDB.find(target.chip);
        if (it != kCpuCapabilityDB.end()) {
            caps_ = it->second;
        } else {
            // 默认：ARM Cortex-A78 级别
            caps_ = kCpuCapabilityDB.at("cortex_a78");
        }
    }

    Result<CpuCompiledModel> generate(const std::vector<IrNode>& ir_nodes) {
        CpuCompiledModel model;

        // 确定架构
        switch (caps_.simd) {
            case SimdLevel::NEON:
            case SimdLevel::NEON_FP16:
                model.arch = "arm64";
                model.simd_level = caps_.simd;
                model.runtime_library = "neon";
                break;
            case SimdLevel::AVX2:
            case SimdLevel::AVX512:
            case SimdLevel::AVX512_VNNI:
                model.arch = "x86_64";
                model.simd_level = caps_.simd;
                model.runtime_library = "avx512";
                break;
            default:
                model.arch = "x86_64";
                model.simd_level = SimdLevel::SCALAR;
                model.runtime_library = "scalar";
                break;
        }

        // 为每种算子生成 CPU kernel
        for (const auto& node : ir_nodes) {
            if (node.op_type == "Conv2D" || node.op_type == "Conv") {
                if (caps_.simd >= SimdLevel::AVX512) {
                    auto k = generate_avx512_conv2d_fp16(3, 32, 3, 3, 320, 320, 1, 1);
                    model.functions.push_back(std::move(k));
                } else {
                    auto k = generate_neon_conv2d_int8(3, 32, 3, 3, 320, 320, 1, 1);
                    model.functions.push_back(std::move(k));
                }
            } else if (node.op_type == "MatMul" || node.op_type == "Gemm") {
                if (caps_.simd >= SimdLevel::NEON_FP16) {
                    auto k = generate_neon_matmul_fp16(256, 256, 256);
                    model.functions.push_back(std::move(k));
                }
            } else if (node.op_type == "Softmax") {
                if (caps_.simd >= SimdLevel::AVX512) {
                    auto k = generate_avx512_softmax(1, 1000);
                    model.functions.push_back(std::move(k));
                }
            }
        }

        // 统计
        model.total_code_bytes = 0;
        for (const auto& f : model.functions) {
            model.total_code_bytes += static_cast<uint32_t>(f.source.size());
        }

        return Ok(std::move(model));
    }

    const CpuCodegenCapabilities& capabilities() const { return caps_; }

private:
    CpuCodegenCapabilities caps_;
};

/**
 * @brief CPU 代码生成入口函数
 */
Result<CpuCompiledModel> generate_cpu_code(
    const std::vector<IrNode>& ir_nodes,
    const CompilationTarget& target) {

    CpuCodeGenerator gen(target);
    return gen.generate(ir_nodes);
}

/**
 * @brief CPU 编译产物序列化为 JSON
 */
std::string cpu_model_to_json(const CpuCompiledModel& model) {
    std::ostringstream json;
    json << "{\n";
    json << "  \"arch\": \"" << model.arch << "\",\n";
    json << "  \"simd_level\": " << static_cast<int>(model.simd_level) << ",\n";
    json << "  \"runtime_library\": \"" << model.runtime_library << "\",\n";
    json << "  \"function_count\": " << model.functions.size() << ",\n";
    json << "  \"total_code_bytes\": " << model.total_code_bytes << ",\n";
    json << "  \"functions\": [\n";

    for (size_t i = 0; i < model.functions.size(); ++i) {
        const auto& f = model.functions[i];
        json << "    {";
        json << "\"name\":\"" << f.name << "\",";
        json << "\"flops\":" << f.estimated_flops << ",";
        json << "\"cycles\":" << f.estimated_cycles << ",";
        json << "\"source_size\":" << f.source.size();
        json << "}";
        if (i + 1 < model.functions.size()) json << ",";
        json << "\n";
    }

    json << "  ]\n}";
    return json.str();
}

} // namespace codegen
} // namespace qoocore
