# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from brain_os.perception import service_pb2 as brain__os_dot_perception_dot_service__pb2
from brain_os.perception import types_pb2 as brain__os_dot_perception_dot_types__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in brain_os/perception/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PerceptionServiceStub:
    """─────────────────────────────────────────────
    PerceptionService — 感知服务 gRPC 接口
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSceneGraph = channel.unary_unary(
                '/brain_os.perception.PerceptionService/GetSceneGraph',
                request_serializer=brain__os_dot_perception_dot_service__pb2.GetSceneGraphRequest.SerializeToString,
                response_deserializer=brain__os_dot_perception_dot_service__pb2.GetSceneGraphResponse.FromString,
                _registered_method=True)
        self.GetLocalization = channel.unary_unary(
                '/brain_os.perception.PerceptionService/GetLocalization',
                request_serializer=brain__os_dot_perception_dot_service__pb2.GetLocalizationRequest.SerializeToString,
                response_deserializer=brain__os_dot_perception_dot_service__pb2.GetLocalizationResponse.FromString,
                _registered_method=True)
        self.QueryObjects = channel.unary_unary(
                '/brain_os.perception.PerceptionService/QueryObjects',
                request_serializer=brain__os_dot_perception_dot_service__pb2.QueryObjectsRequest.SerializeToString,
                response_deserializer=brain__os_dot_perception_dot_service__pb2.QueryObjectsResponse.FromString,
                _registered_method=True)
        self.StreamSceneGraph = channel.unary_stream(
                '/brain_os.perception.PerceptionService/StreamSceneGraph',
                request_serializer=brain__os_dot_perception_dot_service__pb2.StreamSceneGraphRequest.SerializeToString,
                response_deserializer=brain__os_dot_perception_dot_types__pb2.SceneGraph.FromString,
                _registered_method=True)


class PerceptionServiceServicer:
    """─────────────────────────────────────────────
    PerceptionService — 感知服务 gRPC 接口
    ─────────────────────────────────────────────

    """

    def GetSceneGraph(self, request, context):
        """获取当前场景图
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocalization(self, request, context):
        """获取机器人当前位姿
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryObjects(self, request, context):
        """按类别查询目标
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSceneGraph(self, request, context):
        """订阅场景图更新流（Server-Side Streaming）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PerceptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSceneGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSceneGraph,
                    request_deserializer=brain__os_dot_perception_dot_service__pb2.GetSceneGraphRequest.FromString,
                    response_serializer=brain__os_dot_perception_dot_service__pb2.GetSceneGraphResponse.SerializeToString,
            ),
            'GetLocalization': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocalization,
                    request_deserializer=brain__os_dot_perception_dot_service__pb2.GetLocalizationRequest.FromString,
                    response_serializer=brain__os_dot_perception_dot_service__pb2.GetLocalizationResponse.SerializeToString,
            ),
            'QueryObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryObjects,
                    request_deserializer=brain__os_dot_perception_dot_service__pb2.QueryObjectsRequest.FromString,
                    response_serializer=brain__os_dot_perception_dot_service__pb2.QueryObjectsResponse.SerializeToString,
            ),
            'StreamSceneGraph': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSceneGraph,
                    request_deserializer=brain__os_dot_perception_dot_service__pb2.StreamSceneGraphRequest.FromString,
                    response_serializer=brain__os_dot_perception_dot_types__pb2.SceneGraph.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brain_os.perception.PerceptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brain_os.perception.PerceptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PerceptionService:
    """─────────────────────────────────────────────
    PerceptionService — 感知服务 gRPC 接口
    ─────────────────────────────────────────────

    """

    @staticmethod
    def GetSceneGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.perception.PerceptionService/GetSceneGraph',
            brain__os_dot_perception_dot_service__pb2.GetSceneGraphRequest.SerializeToString,
            brain__os_dot_perception_dot_service__pb2.GetSceneGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLocalization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.perception.PerceptionService/GetLocalization',
            brain__os_dot_perception_dot_service__pb2.GetLocalizationRequest.SerializeToString,
            brain__os_dot_perception_dot_service__pb2.GetLocalizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.perception.PerceptionService/QueryObjects',
            brain__os_dot_perception_dot_service__pb2.QueryObjectsRequest.SerializeToString,
            brain__os_dot_perception_dot_service__pb2.QueryObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSceneGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/brain_os.perception.PerceptionService/StreamSceneGraph',
            brain__os_dot_perception_dot_service__pb2.StreamSceneGraphRequest.SerializeToString,
            brain__os_dot_perception_dot_types__pb2.SceneGraph.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
