# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from brain_os.knowledge import service_pb2 as brain__os_dot_knowledge_dot_service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in brain_os/knowledge/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeServiceStub:
    """─────────────────────────────────────────────
    KnowledgeService — 知识服务 gRPC 接口
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchEpisodes = channel.unary_unary(
                '/brain_os.knowledge.KnowledgeService/SearchEpisodes',
                request_serializer=brain__os_dot_knowledge_dot_service__pb2.SearchEpisodesRequest.SerializeToString,
                response_deserializer=brain__os_dot_knowledge_dot_service__pb2.SearchEpisodesResponse.FromString,
                _registered_method=True)
        self.StoreEpisode = channel.unary_unary(
                '/brain_os.knowledge.KnowledgeService/StoreEpisode',
                request_serializer=brain__os_dot_knowledge_dot_service__pb2.StoreEpisodeRequest.SerializeToString,
                response_deserializer=brain__os_dot_knowledge_dot_service__pb2.StoreEpisodeResponse.FromString,
                _registered_method=True)
        self.SearchKnowledge = channel.unary_unary(
                '/brain_os.knowledge.KnowledgeService/SearchKnowledge',
                request_serializer=brain__os_dot_knowledge_dot_service__pb2.SearchKnowledgeRequest.SerializeToString,
                response_deserializer=brain__os_dot_knowledge_dot_service__pb2.SearchKnowledgeResponse.FromString,
                _registered_method=True)
        self.ListSkills = channel.unary_unary(
                '/brain_os.knowledge.KnowledgeService/ListSkills',
                request_serializer=brain__os_dot_knowledge_dot_service__pb2.ListSkillsRequest.SerializeToString,
                response_deserializer=brain__os_dot_knowledge_dot_service__pb2.ListSkillsResponse.FromString,
                _registered_method=True)
        self.RegisterSkill = channel.unary_unary(
                '/brain_os.knowledge.KnowledgeService/RegisterSkill',
                request_serializer=brain__os_dot_knowledge_dot_service__pb2.RegisterSkillRequest.SerializeToString,
                response_deserializer=brain__os_dot_knowledge_dot_service__pb2.RegisterSkillResponse.FromString,
                _registered_method=True)


class KnowledgeServiceServicer:
    """─────────────────────────────────────────────
    KnowledgeService — 知识服务 gRPC 接口
    ─────────────────────────────────────────────

    """

    def SearchEpisodes(self, request, context):
        """向量检索相似情景
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreEpisode(self, request, context):
        """存储新情景
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKnowledge(self, request, context):
        """检索知识条目
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSkills(self, request, context):
        """列出可用技能
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterSkill(self, request, context):
        """注册新技能
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchEpisodes': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchEpisodes,
                    request_deserializer=brain__os_dot_knowledge_dot_service__pb2.SearchEpisodesRequest.FromString,
                    response_serializer=brain__os_dot_knowledge_dot_service__pb2.SearchEpisodesResponse.SerializeToString,
            ),
            'StoreEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreEpisode,
                    request_deserializer=brain__os_dot_knowledge_dot_service__pb2.StoreEpisodeRequest.FromString,
                    response_serializer=brain__os_dot_knowledge_dot_service__pb2.StoreEpisodeResponse.SerializeToString,
            ),
            'SearchKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKnowledge,
                    request_deserializer=brain__os_dot_knowledge_dot_service__pb2.SearchKnowledgeRequest.FromString,
                    response_serializer=brain__os_dot_knowledge_dot_service__pb2.SearchKnowledgeResponse.SerializeToString,
            ),
            'ListSkills': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSkills,
                    request_deserializer=brain__os_dot_knowledge_dot_service__pb2.ListSkillsRequest.FromString,
                    response_serializer=brain__os_dot_knowledge_dot_service__pb2.ListSkillsResponse.SerializeToString,
            ),
            'RegisterSkill': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSkill,
                    request_deserializer=brain__os_dot_knowledge_dot_service__pb2.RegisterSkillRequest.FromString,
                    response_serializer=brain__os_dot_knowledge_dot_service__pb2.RegisterSkillResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brain_os.knowledge.KnowledgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brain_os.knowledge.KnowledgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeService:
    """─────────────────────────────────────────────
    KnowledgeService — 知识服务 gRPC 接口
    ─────────────────────────────────────────────

    """

    @staticmethod
    def SearchEpisodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.knowledge.KnowledgeService/SearchEpisodes',
            brain__os_dot_knowledge_dot_service__pb2.SearchEpisodesRequest.SerializeToString,
            brain__os_dot_knowledge_dot_service__pb2.SearchEpisodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.knowledge.KnowledgeService/StoreEpisode',
            brain__os_dot_knowledge_dot_service__pb2.StoreEpisodeRequest.SerializeToString,
            brain__os_dot_knowledge_dot_service__pb2.StoreEpisodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.knowledge.KnowledgeService/SearchKnowledge',
            brain__os_dot_knowledge_dot_service__pb2.SearchKnowledgeRequest.SerializeToString,
            brain__os_dot_knowledge_dot_service__pb2.SearchKnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSkills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.knowledge.KnowledgeService/ListSkills',
            brain__os_dot_knowledge_dot_service__pb2.ListSkillsRequest.SerializeToString,
            brain__os_dot_knowledge_dot_service__pb2.ListSkillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterSkill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.knowledge.KnowledgeService/RegisterSkill',
            brain__os_dot_knowledge_dot_service__pb2.RegisterSkillRequest.SerializeToString,
            brain__os_dot_knowledge_dot_service__pb2.RegisterSkillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
