server:
  port: 8310

spring:
  application:
    name: qoocommunity-qa
  datasource:
    url: jdbc:postgresql://localhost:5432/qoocommunity
    username: qoobot
    password: qoobot123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
