# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from brain_os.cognition import service_pb2 as brain__os_dot_cognition_dot_service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in brain_os/cognition/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CognitionServiceStub:
    """─────────────────────────────────────────────
    CognitionService — 认知服务 gRPC 接口
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseIntent = channel.unary_unary(
                '/brain_os.cognition.CognitionService/ParseIntent',
                request_serializer=brain__os_dot_cognition_dot_service__pb2.ParseIntentRequest.SerializeToString,
                response_deserializer=brain__os_dot_cognition_dot_service__pb2.ParseIntentResponse.FromString,
                _registered_method=True)
        self.DecomposeTask = channel.unary_unary(
                '/brain_os.cognition.CognitionService/DecomposeTask',
                request_serializer=brain__os_dot_cognition_dot_service__pb2.DecomposeTaskRequest.SerializeToString,
                response_deserializer=brain__os_dot_cognition_dot_service__pb2.DecomposeTaskResponse.FromString,
                _registered_method=True)
        self.GenerateBehaviorTree = channel.unary_unary(
                '/brain_os.cognition.CognitionService/GenerateBehaviorTree',
                request_serializer=brain__os_dot_cognition_dot_service__pb2.GenerateBTRequest.SerializeToString,
                response_deserializer=brain__os_dot_cognition_dot_service__pb2.GenerateBTResponse.FromString,
                _registered_method=True)
        self.Clarify = channel.unary_unary(
                '/brain_os.cognition.CognitionService/Clarify',
                request_serializer=brain__os_dot_cognition_dot_service__pb2.ClarifyRequest.SerializeToString,
                response_deserializer=brain__os_dot_cognition_dot_service__pb2.ClarifyResponse.FromString,
                _registered_method=True)


class CognitionServiceServicer:
    """─────────────────────────────────────────────
    CognitionService — 认知服务 gRPC 接口
    ─────────────────────────────────────────────

    """

    def ParseIntent(self, request, context):
        """自然语言 → 意图解析
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecomposeTask(self, request, context):
        """意图 → 子任务序列
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateBehaviorTree(self, request, context):
        """意图 + 场景图 → 行为树 XML
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clarify(self, request, context):
        """多轮对话澄清
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CognitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseIntent,
                    request_deserializer=brain__os_dot_cognition_dot_service__pb2.ParseIntentRequest.FromString,
                    response_serializer=brain__os_dot_cognition_dot_service__pb2.ParseIntentResponse.SerializeToString,
            ),
            'DecomposeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DecomposeTask,
                    request_deserializer=brain__os_dot_cognition_dot_service__pb2.DecomposeTaskRequest.FromString,
                    response_serializer=brain__os_dot_cognition_dot_service__pb2.DecomposeTaskResponse.SerializeToString,
            ),
            'GenerateBehaviorTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateBehaviorTree,
                    request_deserializer=brain__os_dot_cognition_dot_service__pb2.GenerateBTRequest.FromString,
                    response_serializer=brain__os_dot_cognition_dot_service__pb2.GenerateBTResponse.SerializeToString,
            ),
            'Clarify': grpc.unary_unary_rpc_method_handler(
                    servicer.Clarify,
                    request_deserializer=brain__os_dot_cognition_dot_service__pb2.ClarifyRequest.FromString,
                    response_serializer=brain__os_dot_cognition_dot_service__pb2.ClarifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brain_os.cognition.CognitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brain_os.cognition.CognitionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CognitionService:
    """─────────────────────────────────────────────
    CognitionService — 认知服务 gRPC 接口
    ─────────────────────────────────────────────

    """

    @staticmethod
    def ParseIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.cognition.CognitionService/ParseIntent',
            brain__os_dot_cognition_dot_service__pb2.ParseIntentRequest.SerializeToString,
            brain__os_dot_cognition_dot_service__pb2.ParseIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecomposeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.cognition.CognitionService/DecomposeTask',
            brain__os_dot_cognition_dot_service__pb2.DecomposeTaskRequest.SerializeToString,
            brain__os_dot_cognition_dot_service__pb2.DecomposeTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateBehaviorTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.cognition.CognitionService/GenerateBehaviorTree',
            brain__os_dot_cognition_dot_service__pb2.GenerateBTRequest.SerializeToString,
            brain__os_dot_cognition_dot_service__pb2.GenerateBTResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clarify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.cognition.CognitionService/Clarify',
            brain__os_dot_cognition_dot_service__pb2.ClarifyRequest.SerializeToString,
            brain__os_dot_cognition_dot_service__pb2.ClarifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
