# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain_os/cognition/types.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'brain_os/cognition/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from brain_os.common import types_pb2 as brain__os_dot_common_dot_types__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x62rain_os/cognition/types.proto\x12\x12\x62rain_os.cognition\x1a\x1b\x62rain_os/common/types.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x97\x01\n\x06Intent\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.brain_os.cognition.IntentType\x12\x10\n\x08raw_text\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\'\n\x06params\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x10\n\x08language\x18\x05 \x01(\t\"\xb1\x01\n\x07SubTask\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nskill_name\x18\x02 \x01(\t\x12+\n\nparameters\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x12\n\ndepends_on\x18\x04 \x03(\t\x12.\n\x06status\x18\x05 \x01(\x0e\x32\x1e.brain_os.cognition.TaskStatus\x12\x10\n\x08priority\x18\x06 \x01(\x02\"E\n\x0c\x42\x65haviorTree\x12\x0f\n\x07tree_id\x18\x01 \x01(\t\x12\x0f\n\x07xml_str\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t*\xb6\x01\n\nIntentType\x12\x12\n\x0eINTENT_UNKNOWN\x10\x00\x12\x13\n\x0fINTENT_NAVIGATE\x10\x01\x12\x0f\n\x0bINTENT_PICK\x10\x02\x12\x10\n\x0cINTENT_PLACE\x10\x03\x12\x12\n\x0eINTENT_INSPECT\x10\x04\x12\x10\n\x0cINTENT_GREET\x10\x05\x12\x0f\n\x0bINTENT_STOP\x10\x06\x12\x10\n\x0cINTENT_QUERY\x10\x07\x12\x13\n\x0fINTENT_SEQUENCE\x10\x08*\x81\x01\n\nTaskStatus\x12\x10\n\x0cTASK_PENDING\x10\x00\x12\x10\n\x0cTASK_RUNNING\x10\x01\x12\x12\n\x0eTASK_SUCCEEDED\x10\x02\x12\x0f\n\x0bTASK_FAILED\x10\x03\x12\x12\n\x0eTASK_CANCELLED\x10\x04\x12\x16\n\x12TASK_WAITING_HUMAN\x10\x05\x42\x34Z2github.com/brain-os/brain_proto/brain_os/cognitionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_os.cognition.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/brain-os/brain_proto/brain_os/cognition'
  _globals['_INTENTTYPE']._serialized_start=519
  _globals['_INTENTTYPE']._serialized_end=701
  _globals['_TASKSTATUS']._serialized_start=704
  _globals['_TASKSTATUS']._serialized_end=833
  _globals['_INTENT']._serialized_start=114
  _globals['_INTENT']._serialized_end=265
  _globals['_SUBTASK']._serialized_start=268
  _globals['_SUBTASK']._serialized_end=445
  _globals['_BEHAVIORTREE']._serialized_start=447
  _globals['_BEHAVIORTREE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
