# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain_os/safety/service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'brain_os/safety/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from brain_os.safety import types_pb2 as brain__os_dot_safety_dot_types__pb2
from brain_os.common import types_pb2 as brain__os_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x62rain_os/safety/service.proto\x12\x0f\x62rain_os.safety\x1a\x1b\x62rain_os/safety/types.proto\x1a\x1b\x62rain_os/common/types.proto\",\n\x18GetSafetySnapshotRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\"w\n\x19GetSafetySnapshotResponse\x12\'\n\x06status\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Status\x12\x31\n\x08snapshot\x18\x02 \x01(\x0b\x32\x1f.brain_os.safety.SafetySnapshot\"W\n\x13StreamAlarmsRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12.\n\tmin_level\x18\x02 \x01(\x0e\x32\x1b.brain_os.safety.AlarmLevel\"O\n\x17\x41\x63knowledgeAlarmRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x10\n\x08\x61larm_id\x18\x02 \x01(\t\x12\x10\n\x08operator\x18\x03 \x01(\t\"C\n\x18\x41\x63knowledgeAlarmResponse\x12\'\n\x06status\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Status\"J\n\x17SetVelocityScaleRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\r\n\x05scale\x18\x02 \x01(\x02\x12\x0e\n\x06reason\x18\x03 \x01(\t\"Z\n\x18SetVelocityScaleResponse\x12\'\n\x06status\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Status\x12\x15\n\rapplied_scale\x18\x02 \x01(\x02\x32\xa3\x03\n\rSafetyService\x12j\n\x11GetSafetySnapshot\x12).brain_os.safety.GetSafetySnapshotRequest\x1a*.brain_os.safety.GetSafetySnapshotResponse\x12T\n\x0cStreamAlarms\x12$.brain_os.safety.StreamAlarmsRequest\x1a\x1c.brain_os.safety.SafetyAlarm0\x01\x12g\n\x10\x41\x63knowledgeAlarm\x12(.brain_os.safety.AcknowledgeAlarmRequest\x1a).brain_os.safety.AcknowledgeAlarmResponse\x12g\n\x10SetVelocityScale\x12(.brain_os.safety.SetVelocityScaleRequest\x1a).brain_os.safety.SetVelocityScaleResponseB1Z/github.com/brain-os/brain_proto/brain_os/safetyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_os.safety.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/brain-os/brain_proto/brain_os/safety'
  _globals['_GETSAFETYSNAPSHOTREQUEST']._serialized_start=108
  _globals['_GETSAFETYSNAPSHOTREQUEST']._serialized_end=152
  _globals['_GETSAFETYSNAPSHOTRESPONSE']._serialized_start=154
  _globals['_GETSAFETYSNAPSHOTRESPONSE']._serialized_end=273
  _globals['_STREAMALARMSREQUEST']._serialized_start=275
  _globals['_STREAMALARMSREQUEST']._serialized_end=362
  _globals['_ACKNOWLEDGEALARMREQUEST']._serialized_start=364
  _globals['_ACKNOWLEDGEALARMREQUEST']._serialized_end=443
  _globals['_ACKNOWLEDGEALARMRESPONSE']._serialized_start=445
  _globals['_ACKNOWLEDGEALARMRESPONSE']._serialized_end=512
  _globals['_SETVELOCITYSCALEREQUEST']._serialized_start=514
  _globals['_SETVELOCITYSCALEREQUEST']._serialized_end=588
  _globals['_SETVELOCITYSCALERESPONSE']._serialized_start=590
  _globals['_SETVELOCITYSCALERESPONSE']._serialized_end=680
  _globals['_SAFETYSERVICE']._serialized_start=683
  _globals['_SAFETYSERVICE']._serialized_end=1102
# @@protoc_insertion_point(module_scope)
