# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain_os/perception/types.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'brain_os/perception/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from brain_os.common import types_pb2 as brain__os_dot_common_dot_types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x62rain_os/perception/types.proto\x12\x13\x62rain_os.perception\x1a\x1b\x62rain_os/common/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x01\n\x0e\x44\x65tectedObject\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63lass_label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12,\n\x04\x62\x62ox\x18\x04 \x01(\x0b\x32\x1e.brain_os.common.BoundingBox3D\x12,\n\rpose_in_world\x18\x05 \x01(\x0b\x32\x15.brain_os.common.Pose\x12\x12\n\nattributes\x18\x06 \x03(\t\x12/\n\x0b\x64\x65tected_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"k\n\rSceneRelation\x12\x12\n\nsubject_id\x18\x01 \x01(\t\x12\x11\n\tobject_id\x18\x02 \x01(\t\x12\x33\n\x08relation\x18\x03 \x01(\x0e\x32!.brain_os.perception.RelationType\"\xb3\x01\n\nSceneGraph\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Header\x12\x34\n\x07objects\x18\x02 \x03(\x0b\x32#.brain_os.perception.DetectedObject\x12\x35\n\trelations\x18\x03 \x03(\x0b\x32\".brain_os.perception.SceneRelation\x12\x0f\n\x07summary\x18\x04 \x01(\t\"u\n\x11RobotLocalization\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Header\x12#\n\x04pose\x18\x02 \x01(\x0b\x32\x15.brain_os.common.Pose\x12\x12\n\ncovariance\x18\x03 \x03(\x01\"\x8d\x01\n\x11PointCloudSummary\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Header\x12\x12\n\nnum_points\x18\x02 \x01(\r\x12*\n\x08\x63\x65ntroid\x18\x03 \x01(\x0b\x32\x18.brain_os.common.Vector3\x12\x0f\n\x07\x64\x65nsity\x18\x04 \x01(\x02*j\n\x0cRelationType\x12\x0f\n\x0bREL_UNKNOWN\x10\x00\x12\n\n\x06REL_ON\x10\x01\x12\n\n\x06REL_IN\x10\x02\x12\x0f\n\x0bREL_NEXT_TO\x10\x03\x12\x0e\n\nREL_BEHIND\x10\x04\x12\x10\n\x0cREL_IN_FRONT\x10\x05\x42\x35Z3github.com/brain-os/brain_proto/brain_os/perceptionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_os.perception.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/brain-os/brain_proto/brain_os/perception'
  _globals['_RELATIONTYPE']._serialized_start=912
  _globals['_RELATIONTYPE']._serialized_end=1018
  _globals['_DETECTEDOBJECT']._serialized_start=119
  _globals['_DETECTEDOBJECT']._serialized_end=356
  _globals['_SCENERELATION']._serialized_start=358
  _globals['_SCENERELATION']._serialized_end=465
  _globals['_SCENEGRAPH']._serialized_start=468
  _globals['_SCENEGRAPH']._serialized_end=647
  _globals['_ROBOTLOCALIZATION']._serialized_start=649
  _globals['_ROBOTLOCALIZATION']._serialized_end=766
  _globals['_POINTCLOUDSUMMARY']._serialized_start=769
  _globals['_POINTCLOUDSUMMARY']._serialized_end=910
# @@protoc_insertion_point(module_scope)
