# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain_os/perception/service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'brain_os/perception/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from brain_os.perception import types_pb2 as brain__os_dot_perception_dot_types__pb2
from brain_os.common import types_pb2 as brain__os_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!brain_os/perception/service.proto\x12\x13\x62rain_os.perception\x1a\x1f\x62rain_os/perception/types.proto\x1a\x1b\x62rain_os/common/types.proto\"A\n\x14GetSceneGraphRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x17\n\x0finclude_summary\x18\x02 \x01(\x08\"v\n\x15GetSceneGraphResponse\x12\'\n\x06status\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Status\x12\x34\n\x0bscene_graph\x18\x02 \x01(\x0b\x32\x1f.brain_os.perception.SceneGraph\"*\n\x16GetLocalizationRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\"\x80\x01\n\x17GetLocalizationResponse\x12\'\n\x06status\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Status\x12<\n\x0clocalization\x18\x02 \x01(\x0b\x32&.brain_os.perception.RobotLocalization\"i\n\x13QueryObjectsRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63lass_label\x18\x02 \x01(\t\x12\x16\n\x0emin_confidence\x18\x03 \x01(\x02\x12\x13\n\x0bmax_results\x18\x04 \x01(\r\"u\n\x14QueryObjectsResponse\x12\'\n\x06status\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Status\x12\x34\n\x07objects\x18\x02 \x03(\x0b\x32#.brain_os.perception.DetectedObject\"G\n\x17StreamSceneGraphRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x1a\n\x12update_interval_ms\x18\x02 \x01(\r2\xb3\x03\n\x11PerceptionService\x12\x66\n\rGetSceneGraph\x12).brain_os.perception.GetSceneGraphRequest\x1a*.brain_os.perception.GetSceneGraphResponse\x12l\n\x0fGetLocalization\x12+.brain_os.perception.GetLocalizationRequest\x1a,.brain_os.perception.GetLocalizationResponse\x12\x63\n\x0cQueryObjects\x12(.brain_os.perception.QueryObjectsRequest\x1a).brain_os.perception.QueryObjectsResponse\x12\x63\n\x10StreamSceneGraph\x12,.brain_os.perception.StreamSceneGraphRequest\x1a\x1f.brain_os.perception.SceneGraph0\x01\x42\x35Z3github.com/brain-os/brain_proto/brain_os/perceptionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_os.perception.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/brain-os/brain_proto/brain_os/perception'
  _globals['_GETSCENEGRAPHREQUEST']._serialized_start=120
  _globals['_GETSCENEGRAPHREQUEST']._serialized_end=185
  _globals['_GETSCENEGRAPHRESPONSE']._serialized_start=187
  _globals['_GETSCENEGRAPHRESPONSE']._serialized_end=305
  _globals['_GETLOCALIZATIONREQUEST']._serialized_start=307
  _globals['_GETLOCALIZATIONREQUEST']._serialized_end=349
  _globals['_GETLOCALIZATIONRESPONSE']._serialized_start=352
  _globals['_GETLOCALIZATIONRESPONSE']._serialized_end=480
  _globals['_QUERYOBJECTSREQUEST']._serialized_start=482
  _globals['_QUERYOBJECTSREQUEST']._serialized_end=587
  _globals['_QUERYOBJECTSRESPONSE']._serialized_start=589
  _globals['_QUERYOBJECTSRESPONSE']._serialized_end=706
  _globals['_STREAMSCENEGRAPHREQUEST']._serialized_start=708
  _globals['_STREAMSCENEGRAPHREQUEST']._serialized_end=779
  _globals['_PERCEPTIONSERVICE']._serialized_start=782
  _globals['_PERCEPTIONSERVICE']._serialized_end=1217
# @@protoc_insertion_point(module_scope)
