linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - gocritic
    - prealloc

linters-settings:
  gosec:
    excludes:
      - G104
  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
    - web
  max-issues-per-linter: 50
  max-same-issues: 10
