# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain_os/knowledge/types.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'brain_os/knowledge/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from brain_os.common import types_pb2 as brain__os_dot_common_dot_types__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x62rain_os/knowledge/types.proto\x12\x12\x62rain_os.knowledge\x1a\x1b\x62rain_os/common/types.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n\x05Skill\x12\x10\n\x08skill_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12-\n\x0cparam_schema\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0c\n\x04tags\x18\x06 \x03(\t\"\x80\x02\n\x07\x45pisode\x12\x12\n\nepisode_id\x18\x01 \x01(\t\x12\x10\n\x08robot_id\x18\x02 \x01(\t\x12\x11\n\ttask_type\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x14\n\x0c\x64uration_sec\x18\x05 \x01(\x02\x12(\n\x07\x63ontext\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\x12(\n\x07outcome\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tembedding\x18\t \x03(\x02\"\xc9\x01\n\x0eKnowledgeEntry\x12\x10\n\x08\x65ntry_id\x18\x01 \x01(\t\x12/\n\x04type\x18\x02 \x01(\x0e\x32!.brain_os.knowledge.KnowledgeType\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\tembedding\x18\x04 \x03(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04tags\x18\x07 \x03(\t*p\n\rKnowledgeType\x12\x12\n\x0eKNOWLEDGE_FACT\x10\x00\x12\x17\n\x13KNOWLEDGE_PROCEDURE\x10\x01\x12\x18\n\x14KNOWLEDGE_CONSTRAINT\x10\x02\x12\x18\n\x14KNOWLEDGE_PREFERENCE\x10\x03\x42\x34Z2github.com/brain-os/brain_proto/brain_os/knowledgeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_os.knowledge.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/brain-os/brain_proto/brain_os/knowledge'
  _globals['_KNOWLEDGETYPE']._serialized_start=750
  _globals['_KNOWLEDGETYPE']._serialized_end=862
  _globals['_SKILL']._serialized_start=147
  _globals['_SKILL']._serialized_end=285
  _globals['_EPISODE']._serialized_start=288
  _globals['_EPISODE']._serialized_end=544
  _globals['_KNOWLEDGEENTRY']._serialized_start=547
  _globals['_KNOWLEDGEENTRY']._serialized_end=748
# @@protoc_insertion_point(module_scope)
