// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_QOOMODEL_QOOCORE_H_
#define FLATBUFFERS_GENERATED_QOOMODEL_QOOCORE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace qoocore {

struct QuantizationInfo;
struct QuantizationInfoBuilder;
struct QuantizationInfoT;

struct TensorInfo;
struct TensorInfoBuilder;
struct TensorInfoT;

struct BackendCompiledInfo;
struct BackendCompiledInfoBuilder;
struct BackendCompiledInfoT;

struct ModelWeights;
struct ModelWeightsBuilder;
struct ModelWeightsT;

struct ModelConfig;
struct ModelConfigBuilder;
struct ModelConfigT;

struct ModelMetadata;
struct ModelMetadataBuilder;
struct ModelMetadataT;

struct ModelBenchmark;
struct ModelBenchmarkBuilder;
struct ModelBenchmarkT;

struct AccuracyInfo;
struct AccuracyInfoBuilder;
struct AccuracyInfoT;

struct QooModel;
struct QooModelBuilder;
struct QooModelT;

bool operator==(const QuantizationInfoT &lhs, const QuantizationInfoT &rhs);
bool operator!=(const QuantizationInfoT &lhs, const QuantizationInfoT &rhs);
bool operator==(const TensorInfoT &lhs, const TensorInfoT &rhs);
bool operator!=(const TensorInfoT &lhs, const TensorInfoT &rhs);
bool operator==(const BackendCompiledInfoT &lhs, const BackendCompiledInfoT &rhs);
bool operator!=(const BackendCompiledInfoT &lhs, const BackendCompiledInfoT &rhs);
bool operator==(const ModelWeightsT &lhs, const ModelWeightsT &rhs);
bool operator!=(const ModelWeightsT &lhs, const ModelWeightsT &rhs);
bool operator==(const ModelConfigT &lhs, const ModelConfigT &rhs);
bool operator!=(const ModelConfigT &lhs, const ModelConfigT &rhs);
bool operator==(const ModelMetadataT &lhs, const ModelMetadataT &rhs);
bool operator!=(const ModelMetadataT &lhs, const ModelMetadataT &rhs);
bool operator==(const ModelBenchmarkT &lhs, const ModelBenchmarkT &rhs);
bool operator!=(const ModelBenchmarkT &lhs, const ModelBenchmarkT &rhs);
bool operator==(const AccuracyInfoT &lhs, const AccuracyInfoT &rhs);
bool operator!=(const AccuracyInfoT &lhs, const AccuracyInfoT &rhs);
bool operator==(const QooModelT &lhs, const QooModelT &rhs);
bool operator!=(const QooModelT &lhs, const QooModelT &rhs);

enum BackendType : uint8_t {
  BackendType_NPU_QNN = 0,
  BackendType_NPU_BPU = 1,
  BackendType_NPU_RKNN = 2,
  BackendType_GPU_CUDA = 10,
  BackendType_GPU_OPENCL = 11,
  BackendType_GPU_VULKAN = 12,
  BackendType_CPU_NEON = 20,
  BackendType_CPU_AVX512 = 21,
  BackendType_AUTO = 255,
  BackendType_MIN = BackendType_NPU_QNN,
  BackendType_MAX = BackendType_AUTO
};

inline const BackendType (&EnumValuesBackendType())[9] {
  static const BackendType values[] = {
    BackendType_NPU_QNN,
    BackendType_NPU_BPU,
    BackendType_NPU_RKNN,
    BackendType_GPU_CUDA,
    BackendType_GPU_OPENCL,
    BackendType_GPU_VULKAN,
    BackendType_CPU_NEON,
    BackendType_CPU_AVX512,
    BackendType_AUTO
  };
  return values;
}

inline const char *EnumNameBackendType(BackendType e) {
  switch (e) {
    case BackendType_NPU_QNN: return "NPU_QNN";
    case BackendType_NPU_BPU: return "NPU_BPU";
    case BackendType_NPU_RKNN: return "NPU_RKNN";
    case BackendType_GPU_CUDA: return "GPU_CUDA";
    case BackendType_GPU_OPENCL: return "GPU_OPENCL";
    case BackendType_GPU_VULKAN: return "GPU_VULKAN";
    case BackendType_CPU_NEON: return "CPU_NEON";
    case BackendType_CPU_AVX512: return "CPU_AVX512";
    case BackendType_AUTO: return "AUTO";
    default: return "";
  }
}

enum DType : uint8_t {
  DType_FLOAT32 = 0,
  DType_FLOAT16 = 1,
  DType_FLOAT64 = 2,
  DType_BFLOAT16 = 3,
  DType_INT32 = 10,
  DType_INT16 = 11,
  DType_INT8 = 12,
  DType_INT4 = 13,
  DType_UINT32 = 20,
  DType_UINT16 = 21,
  DType_UINT8 = 22,
  DType_BOOL = 30,
  DType_MIN = DType_FLOAT32,
  DType_MAX = DType_BOOL
};

inline const DType (&EnumValuesDType())[12] {
  static const DType values[] = {
    DType_FLOAT32,
    DType_FLOAT16,
    DType_FLOAT64,
    DType_BFLOAT16,
    DType_INT32,
    DType_INT16,
    DType_INT8,
    DType_INT4,
    DType_UINT32,
    DType_UINT16,
    DType_UINT8,
    DType_BOOL
  };
  return values;
}

inline const char * const *EnumNamesDType() {
  static const char * const names[32] = {
    "FLOAT32",
    "FLOAT16",
    "FLOAT64",
    "BFLOAT16",
    "",
    "",
    "",
    "",
    "",
    "",
    "INT32",
    "INT16",
    "INT8",
    "INT4",
    "",
    "",
    "",
    "",
    "",
    "",
    "UINT32",
    "UINT16",
    "UINT8",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "BOOL",
    nullptr
  };
  return names;
}

inline const char *EnumNameDType(DType e) {
  if (::flatbuffers::IsOutRange(e, DType_FLOAT32, DType_BOOL)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDType()[index];
}

enum TensorLayout : uint8_t {
  TensorLayout_NCHW = 0,
  TensorLayout_NHWC = 1,
  TensorLayout_NC = 2,
  TensorLayout_NCDHW = 3,
  TensorLayout_MIN = TensorLayout_NCHW,
  TensorLayout_MAX = TensorLayout_NCDHW
};

inline const TensorLayout (&EnumValuesTensorLayout())[4] {
  static const TensorLayout values[] = {
    TensorLayout_NCHW,
    TensorLayout_NHWC,
    TensorLayout_NC,
    TensorLayout_NCDHW
  };
  return values;
}

inline const char * const *EnumNamesTensorLayout() {
  static const char * const names[5] = {
    "NCHW",
    "NHWC",
    "NC",
    "NCDHW",
    nullptr
  };
  return names;
}

inline const char *EnumNameTensorLayout(TensorLayout e) {
  if (::flatbuffers::IsOutRange(e, TensorLayout_NCHW, TensorLayout_NCDHW)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTensorLayout()[index];
}

struct QuantizationInfoT : public ::flatbuffers::NativeTable {
  typedef QuantizationInfo TableType;
  qoocore::DType dtype = qoocore::DType_FLOAT32;
  std::vector<float> scales{};
  std::vector<int32_t> zero_points{};
  bool per_channel = false;
};

struct QuantizationInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef QuantizationInfoT NativeTableType;
  typedef QuantizationInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DTYPE = 4,
    VT_SCALES = 6,
    VT_ZERO_POINTS = 8,
    VT_PER_CHANNEL = 10
  };
  qoocore::DType dtype() const {
    return static_cast<qoocore::DType>(GetField<uint8_t>(VT_DTYPE, 0));
  }
  const ::flatbuffers::Vector<float> *scales() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_SCALES);
  }
  const ::flatbuffers::Vector<int32_t> *zero_points() const {
    return GetPointer<const ::flatbuffers::Vector<int32_t> *>(VT_ZERO_POINTS);
  }
  bool per_channel() const {
    return GetField<uint8_t>(VT_PER_CHANNEL, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_DTYPE, 1) &&
           VerifyOffset(verifier, VT_SCALES) &&
           verifier.VerifyVector(scales()) &&
           VerifyOffset(verifier, VT_ZERO_POINTS) &&
           verifier.VerifyVector(zero_points()) &&
           VerifyField<uint8_t>(verifier, VT_PER_CHANNEL, 1) &&
           verifier.EndTable();
  }
  QuantizationInfoT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(QuantizationInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<QuantizationInfo> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const QuantizationInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct QuantizationInfoBuilder {
  typedef QuantizationInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_dtype(qoocore::DType dtype) {
    fbb_.AddElement<uint8_t>(QuantizationInfo::VT_DTYPE, static_cast<uint8_t>(dtype), 0);
  }
  void add_scales(::flatbuffers::Offset<::flatbuffers::Vector<float>> scales) {
    fbb_.AddOffset(QuantizationInfo::VT_SCALES, scales);
  }
  void add_zero_points(::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> zero_points) {
    fbb_.AddOffset(QuantizationInfo::VT_ZERO_POINTS, zero_points);
  }
  void add_per_channel(bool per_channel) {
    fbb_.AddElement<uint8_t>(QuantizationInfo::VT_PER_CHANNEL, static_cast<uint8_t>(per_channel), 0);
  }
  explicit QuantizationInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<QuantizationInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<QuantizationInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<QuantizationInfo> CreateQuantizationInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    qoocore::DType dtype = qoocore::DType_FLOAT32,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> scales = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int32_t>> zero_points = 0,
    bool per_channel = false) {
  QuantizationInfoBuilder builder_(_fbb);
  builder_.add_zero_points(zero_points);
  builder_.add_scales(scales);
  builder_.add_per_channel(per_channel);
  builder_.add_dtype(dtype);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<QuantizationInfo> CreateQuantizationInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    qoocore::DType dtype = qoocore::DType_FLOAT32,
    const std::vector<float> *scales = nullptr,
    const std::vector<int32_t> *zero_points = nullptr,
    bool per_channel = false) {
  auto scales__ = scales ? _fbb.CreateVector<float>(*scales) : 0;
  auto zero_points__ = zero_points ? _fbb.CreateVector<int32_t>(*zero_points) : 0;
  return qoocore::CreateQuantizationInfo(
      _fbb,
      dtype,
      scales__,
      zero_points__,
      per_channel);
}

::flatbuffers::Offset<QuantizationInfo> CreateQuantizationInfo(::flatbuffers::FlatBufferBuilder &_fbb, const QuantizationInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct TensorInfoT : public ::flatbuffers::NativeTable {
  typedef TensorInfo TableType;
  std::string name{};
  qoocore::DType dtype = qoocore::DType_FLOAT32;
  qoocore::TensorLayout layout = qoocore::TensorLayout_NCHW;
  std::vector<uint32_t> shape{};
  std::unique_ptr<qoocore::QuantizationInfoT> quant{};
  std::string description{};
  TensorInfoT() = default;
  TensorInfoT(const TensorInfoT &o);
  TensorInfoT(TensorInfoT&&) FLATBUFFERS_NOEXCEPT = default;
  TensorInfoT &operator=(TensorInfoT o) FLATBUFFERS_NOEXCEPT;
};

struct TensorInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TensorInfoT NativeTableType;
  typedef TensorInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_DTYPE = 6,
    VT_LAYOUT = 8,
    VT_SHAPE = 10,
    VT_QUANT = 12,
    VT_DESCRIPTION = 14
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  qoocore::DType dtype() const {
    return static_cast<qoocore::DType>(GetField<uint8_t>(VT_DTYPE, 0));
  }
  qoocore::TensorLayout layout() const {
    return static_cast<qoocore::TensorLayout>(GetField<uint8_t>(VT_LAYOUT, 0));
  }
  const ::flatbuffers::Vector<uint32_t> *shape() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_SHAPE);
  }
  const qoocore::QuantizationInfo *quant() const {
    return GetPointer<const qoocore::QuantizationInfo *>(VT_QUANT);
  }
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_DTYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_LAYOUT, 1) &&
           VerifyOffset(verifier, VT_SHAPE) &&
           verifier.VerifyVector(shape()) &&
           VerifyOffset(verifier, VT_QUANT) &&
           verifier.VerifyTable(quant()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           verifier.EndTable();
  }
  TensorInfoT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TensorInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TensorInfo> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TensorInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TensorInfoBuilder {
  typedef TensorInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(TensorInfo::VT_NAME, name);
  }
  void add_dtype(qoocore::DType dtype) {
    fbb_.AddElement<uint8_t>(TensorInfo::VT_DTYPE, static_cast<uint8_t>(dtype), 0);
  }
  void add_layout(qoocore::TensorLayout layout) {
    fbb_.AddElement<uint8_t>(TensorInfo::VT_LAYOUT, static_cast<uint8_t>(layout), 0);
  }
  void add_shape(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> shape) {
    fbb_.AddOffset(TensorInfo::VT_SHAPE, shape);
  }
  void add_quant(::flatbuffers::Offset<qoocore::QuantizationInfo> quant) {
    fbb_.AddOffset(TensorInfo::VT_QUANT, quant);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(TensorInfo::VT_DESCRIPTION, description);
  }
  explicit TensorInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TensorInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TensorInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TensorInfo> CreateTensorInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    qoocore::DType dtype = qoocore::DType_FLOAT32,
    qoocore::TensorLayout layout = qoocore::TensorLayout_NCHW,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> shape = 0,
    ::flatbuffers::Offset<qoocore::QuantizationInfo> quant = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0) {
  TensorInfoBuilder builder_(_fbb);
  builder_.add_description(description);
  builder_.add_quant(quant);
  builder_.add_shape(shape);
  builder_.add_name(name);
  builder_.add_layout(layout);
  builder_.add_dtype(dtype);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TensorInfo> CreateTensorInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    qoocore::DType dtype = qoocore::DType_FLOAT32,
    qoocore::TensorLayout layout = qoocore::TensorLayout_NCHW,
    const std::vector<uint32_t> *shape = nullptr,
    ::flatbuffers::Offset<qoocore::QuantizationInfo> quant = 0,
    const char *description = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto shape__ = shape ? _fbb.CreateVector<uint32_t>(*shape) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  return qoocore::CreateTensorInfo(
      _fbb,
      name__,
      dtype,
      layout,
      shape__,
      quant,
      description__);
}

::flatbuffers::Offset<TensorInfo> CreateTensorInfo(::flatbuffers::FlatBufferBuilder &_fbb, const TensorInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BackendCompiledInfoT : public ::flatbuffers::NativeTable {
  typedef BackendCompiledInfo TableType;
  qoocore::BackendType backend_type = qoocore::BackendType_NPU_QNN;
  std::vector<uint8_t> compiled_data{};
  std::string backend_config{};
  float estimated_latency_ms = 0.0f;
  float estimated_memory_mb = 0.0f;
};

struct BackendCompiledInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BackendCompiledInfoT NativeTableType;
  typedef BackendCompiledInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BACKEND_TYPE = 4,
    VT_COMPILED_DATA = 6,
    VT_BACKEND_CONFIG = 8,
    VT_ESTIMATED_LATENCY_MS = 10,
    VT_ESTIMATED_MEMORY_MB = 12
  };
  qoocore::BackendType backend_type() const {
    return static_cast<qoocore::BackendType>(GetField<uint8_t>(VT_BACKEND_TYPE, 0));
  }
  const ::flatbuffers::Vector<uint8_t> *compiled_data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_COMPILED_DATA);
  }
  const ::flatbuffers::String *backend_config() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BACKEND_CONFIG);
  }
  float estimated_latency_ms() const {
    return GetField<float>(VT_ESTIMATED_LATENCY_MS, 0.0f);
  }
  float estimated_memory_mb() const {
    return GetField<float>(VT_ESTIMATED_MEMORY_MB, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BACKEND_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_COMPILED_DATA) &&
           verifier.VerifyVector(compiled_data()) &&
           VerifyOffset(verifier, VT_BACKEND_CONFIG) &&
           verifier.VerifyString(backend_config()) &&
           VerifyField<float>(verifier, VT_ESTIMATED_LATENCY_MS, 4) &&
           VerifyField<float>(verifier, VT_ESTIMATED_MEMORY_MB, 4) &&
           verifier.EndTable();
  }
  BackendCompiledInfoT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BackendCompiledInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BackendCompiledInfo> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BackendCompiledInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BackendCompiledInfoBuilder {
  typedef BackendCompiledInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_backend_type(qoocore::BackendType backend_type) {
    fbb_.AddElement<uint8_t>(BackendCompiledInfo::VT_BACKEND_TYPE, static_cast<uint8_t>(backend_type), 0);
  }
  void add_compiled_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> compiled_data) {
    fbb_.AddOffset(BackendCompiledInfo::VT_COMPILED_DATA, compiled_data);
  }
  void add_backend_config(::flatbuffers::Offset<::flatbuffers::String> backend_config) {
    fbb_.AddOffset(BackendCompiledInfo::VT_BACKEND_CONFIG, backend_config);
  }
  void add_estimated_latency_ms(float estimated_latency_ms) {
    fbb_.AddElement<float>(BackendCompiledInfo::VT_ESTIMATED_LATENCY_MS, estimated_latency_ms, 0.0f);
  }
  void add_estimated_memory_mb(float estimated_memory_mb) {
    fbb_.AddElement<float>(BackendCompiledInfo::VT_ESTIMATED_MEMORY_MB, estimated_memory_mb, 0.0f);
  }
  explicit BackendCompiledInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BackendCompiledInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BackendCompiledInfo>(end);
    fbb_.Required(o, BackendCompiledInfo::VT_COMPILED_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<BackendCompiledInfo> CreateBackendCompiledInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    qoocore::BackendType backend_type = qoocore::BackendType_NPU_QNN,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> compiled_data = 0,
    ::flatbuffers::Offset<::flatbuffers::String> backend_config = 0,
    float estimated_latency_ms = 0.0f,
    float estimated_memory_mb = 0.0f) {
  BackendCompiledInfoBuilder builder_(_fbb);
  builder_.add_estimated_memory_mb(estimated_memory_mb);
  builder_.add_estimated_latency_ms(estimated_latency_ms);
  builder_.add_backend_config(backend_config);
  builder_.add_compiled_data(compiled_data);
  builder_.add_backend_type(backend_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BackendCompiledInfo> CreateBackendCompiledInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    qoocore::BackendType backend_type = qoocore::BackendType_NPU_QNN,
    const std::vector<uint8_t> *compiled_data = nullptr,
    const char *backend_config = nullptr,
    float estimated_latency_ms = 0.0f,
    float estimated_memory_mb = 0.0f) {
  auto compiled_data__ = compiled_data ? _fbb.CreateVector<uint8_t>(*compiled_data) : 0;
  auto backend_config__ = backend_config ? _fbb.CreateString(backend_config) : 0;
  return qoocore::CreateBackendCompiledInfo(
      _fbb,
      backend_type,
      compiled_data__,
      backend_config__,
      estimated_latency_ms,
      estimated_memory_mb);
}

::flatbuffers::Offset<BackendCompiledInfo> CreateBackendCompiledInfo(::flatbuffers::FlatBufferBuilder &_fbb, const BackendCompiledInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ModelWeightsT : public ::flatbuffers::NativeTable {
  typedef ModelWeights TableType;
  std::vector<uint8_t> weights_data{};
  uint64_t weight_size = 0;
  std::vector<std::unique_ptr<qoocore::TensorInfoT>> weight_tensors{};
  ModelWeightsT() = default;
  ModelWeightsT(const ModelWeightsT &o);
  ModelWeightsT(ModelWeightsT&&) FLATBUFFERS_NOEXCEPT = default;
  ModelWeightsT &operator=(ModelWeightsT o) FLATBUFFERS_NOEXCEPT;
};

struct ModelWeights FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelWeightsT NativeTableType;
  typedef ModelWeightsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WEIGHTS_DATA = 4,
    VT_WEIGHT_SIZE = 6,
    VT_WEIGHT_TENSORS = 8
  };
  const ::flatbuffers::Vector<uint8_t> *weights_data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_WEIGHTS_DATA);
  }
  uint64_t weight_size() const {
    return GetField<uint64_t>(VT_WEIGHT_SIZE, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<qoocore::TensorInfo>> *weight_tensors() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<qoocore::TensorInfo>> *>(VT_WEIGHT_TENSORS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_WEIGHTS_DATA) &&
           verifier.VerifyVector(weights_data()) &&
           VerifyField<uint64_t>(verifier, VT_WEIGHT_SIZE, 8) &&
           VerifyOffset(verifier, VT_WEIGHT_TENSORS) &&
           verifier.VerifyVector(weight_tensors()) &&
           verifier.VerifyVectorOfTables(weight_tensors()) &&
           verifier.EndTable();
  }
  ModelWeightsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ModelWeightsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ModelWeights> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ModelWeightsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ModelWeightsBuilder {
  typedef ModelWeights Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_weights_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> weights_data) {
    fbb_.AddOffset(ModelWeights::VT_WEIGHTS_DATA, weights_data);
  }
  void add_weight_size(uint64_t weight_size) {
    fbb_.AddElement<uint64_t>(ModelWeights::VT_WEIGHT_SIZE, weight_size, 0);
  }
  void add_weight_tensors(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<qoocore::TensorInfo>>> weight_tensors) {
    fbb_.AddOffset(ModelWeights::VT_WEIGHT_TENSORS, weight_tensors);
  }
  explicit ModelWeightsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModelWeights> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModelWeights>(end);
    fbb_.Required(o, ModelWeights::VT_WEIGHTS_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<ModelWeights> CreateModelWeights(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> weights_data = 0,
    uint64_t weight_size = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<qoocore::TensorInfo>>> weight_tensors = 0) {
  ModelWeightsBuilder builder_(_fbb);
  builder_.add_weight_size(weight_size);
  builder_.add_weight_tensors(weight_tensors);
  builder_.add_weights_data(weights_data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModelWeights> CreateModelWeightsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *weights_data = nullptr,
    uint64_t weight_size = 0,
    const std::vector<::flatbuffers::Offset<qoocore::TensorInfo>> *weight_tensors = nullptr) {
  auto weights_data__ = weights_data ? _fbb.CreateVector<uint8_t>(*weights_data) : 0;
  auto weight_tensors__ = weight_tensors ? _fbb.CreateVector<::flatbuffers::Offset<qoocore::TensorInfo>>(*weight_tensors) : 0;
  return qoocore::CreateModelWeights(
      _fbb,
      weights_data__,
      weight_size,
      weight_tensors__);
}

::flatbuffers::Offset<ModelWeights> CreateModelWeights(::flatbuffers::FlatBufferBuilder &_fbb, const ModelWeightsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ModelConfigT : public ::flatbuffers::NativeTable {
  typedef ModelConfig TableType;
  uint8_t optimization_level = 2;
  std::string quant_scheme{};
  uint32_t calibration_samples = 100;
  std::string target_chip{};
  bool support_dynamic_batch = false;
  uint32_t max_batch_size = 1;
};

struct ModelConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelConfigT NativeTableType;
  typedef ModelConfigBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OPTIMIZATION_LEVEL = 4,
    VT_QUANT_SCHEME = 6,
    VT_CALIBRATION_SAMPLES = 8,
    VT_TARGET_CHIP = 10,
    VT_SUPPORT_DYNAMIC_BATCH = 12,
    VT_MAX_BATCH_SIZE = 14
  };
  uint8_t optimization_level() const {
    return GetField<uint8_t>(VT_OPTIMIZATION_LEVEL, 2);
  }
  const ::flatbuffers::String *quant_scheme() const {
    return GetPointer<const ::flatbuffers::String *>(VT_QUANT_SCHEME);
  }
  uint32_t calibration_samples() const {
    return GetField<uint32_t>(VT_CALIBRATION_SAMPLES, 100);
  }
  const ::flatbuffers::String *target_chip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TARGET_CHIP);
  }
  bool support_dynamic_batch() const {
    return GetField<uint8_t>(VT_SUPPORT_DYNAMIC_BATCH, 0) != 0;
  }
  uint32_t max_batch_size() const {
    return GetField<uint32_t>(VT_MAX_BATCH_SIZE, 1);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_OPTIMIZATION_LEVEL, 1) &&
           VerifyOffset(verifier, VT_QUANT_SCHEME) &&
           verifier.VerifyString(quant_scheme()) &&
           VerifyField<uint32_t>(verifier, VT_CALIBRATION_SAMPLES, 4) &&
           VerifyOffset(verifier, VT_TARGET_CHIP) &&
           verifier.VerifyString(target_chip()) &&
           VerifyField<uint8_t>(verifier, VT_SUPPORT_DYNAMIC_BATCH, 1) &&
           VerifyField<uint32_t>(verifier, VT_MAX_BATCH_SIZE, 4) &&
           verifier.EndTable();
  }
  ModelConfigT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ModelConfigT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ModelConfig> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ModelConfigT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ModelConfigBuilder {
  typedef ModelConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_optimization_level(uint8_t optimization_level) {
    fbb_.AddElement<uint8_t>(ModelConfig::VT_OPTIMIZATION_LEVEL, optimization_level, 2);
  }
  void add_quant_scheme(::flatbuffers::Offset<::flatbuffers::String> quant_scheme) {
    fbb_.AddOffset(ModelConfig::VT_QUANT_SCHEME, quant_scheme);
  }
  void add_calibration_samples(uint32_t calibration_samples) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_CALIBRATION_SAMPLES, calibration_samples, 100);
  }
  void add_target_chip(::flatbuffers::Offset<::flatbuffers::String> target_chip) {
    fbb_.AddOffset(ModelConfig::VT_TARGET_CHIP, target_chip);
  }
  void add_support_dynamic_batch(bool support_dynamic_batch) {
    fbb_.AddElement<uint8_t>(ModelConfig::VT_SUPPORT_DYNAMIC_BATCH, static_cast<uint8_t>(support_dynamic_batch), 0);
  }
  void add_max_batch_size(uint32_t max_batch_size) {
    fbb_.AddElement<uint32_t>(ModelConfig::VT_MAX_BATCH_SIZE, max_batch_size, 1);
  }
  explicit ModelConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModelConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModelConfig>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModelConfig> CreateModelConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t optimization_level = 2,
    ::flatbuffers::Offset<::flatbuffers::String> quant_scheme = 0,
    uint32_t calibration_samples = 100,
    ::flatbuffers::Offset<::flatbuffers::String> target_chip = 0,
    bool support_dynamic_batch = false,
    uint32_t max_batch_size = 1) {
  ModelConfigBuilder builder_(_fbb);
  builder_.add_max_batch_size(max_batch_size);
  builder_.add_target_chip(target_chip);
  builder_.add_calibration_samples(calibration_samples);
  builder_.add_quant_scheme(quant_scheme);
  builder_.add_support_dynamic_batch(support_dynamic_batch);
  builder_.add_optimization_level(optimization_level);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModelConfig> CreateModelConfigDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t optimization_level = 2,
    const char *quant_scheme = nullptr,
    uint32_t calibration_samples = 100,
    const char *target_chip = nullptr,
    bool support_dynamic_batch = false,
    uint32_t max_batch_size = 1) {
  auto quant_scheme__ = quant_scheme ? _fbb.CreateString(quant_scheme) : 0;
  auto target_chip__ = target_chip ? _fbb.CreateString(target_chip) : 0;
  return qoocore::CreateModelConfig(
      _fbb,
      optimization_level,
      quant_scheme__,
      calibration_samples,
      target_chip__,
      support_dynamic_batch,
      max_batch_size);
}

::flatbuffers::Offset<ModelConfig> CreateModelConfig(::flatbuffers::FlatBufferBuilder &_fbb, const ModelConfigT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ModelMetadataT : public ::flatbuffers::NativeTable {
  typedef ModelMetadata TableType;
  std::string source_format{};
  std::string source_path{};
  uint32_t source_opset = 0;
  std::string export_date{};
  std::string compiler_version{};
  std::string compile_date{};
  std::string compile_host{};
  std::unique_ptr<qoocore::ModelBenchmarkT> benchmark{};
  std::unique_ptr<qoocore::AccuracyInfoT> accuracy{};
  std::string extra{};
  ModelMetadataT() = default;
  ModelMetadataT(const ModelMetadataT &o);
  ModelMetadataT(ModelMetadataT&&) FLATBUFFERS_NOEXCEPT = default;
  ModelMetadataT &operator=(ModelMetadataT o) FLATBUFFERS_NOEXCEPT;
};

struct ModelMetadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelMetadataT NativeTableType;
  typedef ModelMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SOURCE_FORMAT = 4,
    VT_SOURCE_PATH = 6,
    VT_SOURCE_OPSET = 8,
    VT_EXPORT_DATE = 10,
    VT_COMPILER_VERSION = 12,
    VT_COMPILE_DATE = 14,
    VT_COMPILE_HOST = 16,
    VT_BENCHMARK = 18,
    VT_ACCURACY = 20,
    VT_EXTRA = 22
  };
  const ::flatbuffers::String *source_format() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_FORMAT);
  }
  const ::flatbuffers::String *source_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE_PATH);
  }
  uint32_t source_opset() const {
    return GetField<uint32_t>(VT_SOURCE_OPSET, 0);
  }
  const ::flatbuffers::String *export_date() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXPORT_DATE);
  }
  const ::flatbuffers::String *compiler_version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COMPILER_VERSION);
  }
  const ::flatbuffers::String *compile_date() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COMPILE_DATE);
  }
  const ::flatbuffers::String *compile_host() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COMPILE_HOST);
  }
  const qoocore::ModelBenchmark *benchmark() const {
    return GetPointer<const qoocore::ModelBenchmark *>(VT_BENCHMARK);
  }
  const qoocore::AccuracyInfo *accuracy() const {
    return GetPointer<const qoocore::AccuracyInfo *>(VT_ACCURACY);
  }
  const ::flatbuffers::String *extra() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXTRA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SOURCE_FORMAT) &&
           verifier.VerifyString(source_format()) &&
           VerifyOffset(verifier, VT_SOURCE_PATH) &&
           verifier.VerifyString(source_path()) &&
           VerifyField<uint32_t>(verifier, VT_SOURCE_OPSET, 4) &&
           VerifyOffset(verifier, VT_EXPORT_DATE) &&
           verifier.VerifyString(export_date()) &&
           VerifyOffset(verifier, VT_COMPILER_VERSION) &&
           verifier.VerifyString(compiler_version()) &&
           VerifyOffset(verifier, VT_COMPILE_DATE) &&
           verifier.VerifyString(compile_date()) &&
           VerifyOffset(verifier, VT_COMPILE_HOST) &&
           verifier.VerifyString(compile_host()) &&
           VerifyOffset(verifier, VT_BENCHMARK) &&
           verifier.VerifyTable(benchmark()) &&
           VerifyOffset(verifier, VT_ACCURACY) &&
           verifier.VerifyTable(accuracy()) &&
           VerifyOffset(verifier, VT_EXTRA) &&
           verifier.VerifyString(extra()) &&
           verifier.EndTable();
  }
  ModelMetadataT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ModelMetadataT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ModelMetadata> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ModelMetadataT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ModelMetadataBuilder {
  typedef ModelMetadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_source_format(::flatbuffers::Offset<::flatbuffers::String> source_format) {
    fbb_.AddOffset(ModelMetadata::VT_SOURCE_FORMAT, source_format);
  }
  void add_source_path(::flatbuffers::Offset<::flatbuffers::String> source_path) {
    fbb_.AddOffset(ModelMetadata::VT_SOURCE_PATH, source_path);
  }
  void add_source_opset(uint32_t source_opset) {
    fbb_.AddElement<uint32_t>(ModelMetadata::VT_SOURCE_OPSET, source_opset, 0);
  }
  void add_export_date(::flatbuffers::Offset<::flatbuffers::String> export_date) {
    fbb_.AddOffset(ModelMetadata::VT_EXPORT_DATE, export_date);
  }
  void add_compiler_version(::flatbuffers::Offset<::flatbuffers::String> compiler_version) {
    fbb_.AddOffset(ModelMetadata::VT_COMPILER_VERSION, compiler_version);
  }
  void add_compile_date(::flatbuffers::Offset<::flatbuffers::String> compile_date) {
    fbb_.AddOffset(ModelMetadata::VT_COMPILE_DATE, compile_date);
  }
  void add_compile_host(::flatbuffers::Offset<::flatbuffers::String> compile_host) {
    fbb_.AddOffset(ModelMetadata::VT_COMPILE_HOST, compile_host);
  }
  void add_benchmark(::flatbuffers::Offset<qoocore::ModelBenchmark> benchmark) {
    fbb_.AddOffset(ModelMetadata::VT_BENCHMARK, benchmark);
  }
  void add_accuracy(::flatbuffers::Offset<qoocore::AccuracyInfo> accuracy) {
    fbb_.AddOffset(ModelMetadata::VT_ACCURACY, accuracy);
  }
  void add_extra(::flatbuffers::Offset<::flatbuffers::String> extra) {
    fbb_.AddOffset(ModelMetadata::VT_EXTRA, extra);
  }
  explicit ModelMetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModelMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModelMetadata>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModelMetadata> CreateModelMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> source_format = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source_path = 0,
    uint32_t source_opset = 0,
    ::flatbuffers::Offset<::flatbuffers::String> export_date = 0,
    ::flatbuffers::Offset<::flatbuffers::String> compiler_version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> compile_date = 0,
    ::flatbuffers::Offset<::flatbuffers::String> compile_host = 0,
    ::flatbuffers::Offset<qoocore::ModelBenchmark> benchmark = 0,
    ::flatbuffers::Offset<qoocore::AccuracyInfo> accuracy = 0,
    ::flatbuffers::Offset<::flatbuffers::String> extra = 0) {
  ModelMetadataBuilder builder_(_fbb);
  builder_.add_extra(extra);
  builder_.add_accuracy(accuracy);
  builder_.add_benchmark(benchmark);
  builder_.add_compile_host(compile_host);
  builder_.add_compile_date(compile_date);
  builder_.add_compiler_version(compiler_version);
  builder_.add_export_date(export_date);
  builder_.add_source_opset(source_opset);
  builder_.add_source_path(source_path);
  builder_.add_source_format(source_format);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModelMetadata> CreateModelMetadataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *source_format = nullptr,
    const char *source_path = nullptr,
    uint32_t source_opset = 0,
    const char *export_date = nullptr,
    const char *compiler_version = nullptr,
    const char *compile_date = nullptr,
    const char *compile_host = nullptr,
    ::flatbuffers::Offset<qoocore::ModelBenchmark> benchmark = 0,
    ::flatbuffers::Offset<qoocore::AccuracyInfo> accuracy = 0,
    const char *extra = nullptr) {
  auto source_format__ = source_format ? _fbb.CreateString(source_format) : 0;
  auto source_path__ = source_path ? _fbb.CreateString(source_path) : 0;
  auto export_date__ = export_date ? _fbb.CreateString(export_date) : 0;
  auto compiler_version__ = compiler_version ? _fbb.CreateString(compiler_version) : 0;
  auto compile_date__ = compile_date ? _fbb.CreateString(compile_date) : 0;
  auto compile_host__ = compile_host ? _fbb.CreateString(compile_host) : 0;
  auto extra__ = extra ? _fbb.CreateString(extra) : 0;
  return qoocore::CreateModelMetadata(
      _fbb,
      source_format__,
      source_path__,
      source_opset,
      export_date__,
      compiler_version__,
      compile_date__,
      compile_host__,
      benchmark,
      accuracy,
      extra__);
}

::flatbuffers::Offset<ModelMetadata> CreateModelMetadata(::flatbuffers::FlatBufferBuilder &_fbb, const ModelMetadataT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ModelBenchmarkT : public ::flatbuffers::NativeTable {
  typedef ModelBenchmark TableType;
  float p50_latency_ms = 0.0f;
  float p90_latency_ms = 0.0f;
  float p99_latency_ms = 0.0f;
  float peak_memory_mb = 0.0f;
  float weight_memory_mb = 0.0f;
  float throughput_fps = 0.0f;
};

struct ModelBenchmark FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelBenchmarkT NativeTableType;
  typedef ModelBenchmarkBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_P50_LATENCY_MS = 4,
    VT_P90_LATENCY_MS = 6,
    VT_P99_LATENCY_MS = 8,
    VT_PEAK_MEMORY_MB = 10,
    VT_WEIGHT_MEMORY_MB = 12,
    VT_THROUGHPUT_FPS = 14
  };
  float p50_latency_ms() const {
    return GetField<float>(VT_P50_LATENCY_MS, 0.0f);
  }
  float p90_latency_ms() const {
    return GetField<float>(VT_P90_LATENCY_MS, 0.0f);
  }
  float p99_latency_ms() const {
    return GetField<float>(VT_P99_LATENCY_MS, 0.0f);
  }
  float peak_memory_mb() const {
    return GetField<float>(VT_PEAK_MEMORY_MB, 0.0f);
  }
  float weight_memory_mb() const {
    return GetField<float>(VT_WEIGHT_MEMORY_MB, 0.0f);
  }
  float throughput_fps() const {
    return GetField<float>(VT_THROUGHPUT_FPS, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_P50_LATENCY_MS, 4) &&
           VerifyField<float>(verifier, VT_P90_LATENCY_MS, 4) &&
           VerifyField<float>(verifier, VT_P99_LATENCY_MS, 4) &&
           VerifyField<float>(verifier, VT_PEAK_MEMORY_MB, 4) &&
           VerifyField<float>(verifier, VT_WEIGHT_MEMORY_MB, 4) &&
           VerifyField<float>(verifier, VT_THROUGHPUT_FPS, 4) &&
           verifier.EndTable();
  }
  ModelBenchmarkT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ModelBenchmarkT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ModelBenchmark> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ModelBenchmarkT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ModelBenchmarkBuilder {
  typedef ModelBenchmark Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_p50_latency_ms(float p50_latency_ms) {
    fbb_.AddElement<float>(ModelBenchmark::VT_P50_LATENCY_MS, p50_latency_ms, 0.0f);
  }
  void add_p90_latency_ms(float p90_latency_ms) {
    fbb_.AddElement<float>(ModelBenchmark::VT_P90_LATENCY_MS, p90_latency_ms, 0.0f);
  }
  void add_p99_latency_ms(float p99_latency_ms) {
    fbb_.AddElement<float>(ModelBenchmark::VT_P99_LATENCY_MS, p99_latency_ms, 0.0f);
  }
  void add_peak_memory_mb(float peak_memory_mb) {
    fbb_.AddElement<float>(ModelBenchmark::VT_PEAK_MEMORY_MB, peak_memory_mb, 0.0f);
  }
  void add_weight_memory_mb(float weight_memory_mb) {
    fbb_.AddElement<float>(ModelBenchmark::VT_WEIGHT_MEMORY_MB, weight_memory_mb, 0.0f);
  }
  void add_throughput_fps(float throughput_fps) {
    fbb_.AddElement<float>(ModelBenchmark::VT_THROUGHPUT_FPS, throughput_fps, 0.0f);
  }
  explicit ModelBenchmarkBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModelBenchmark> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModelBenchmark>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModelBenchmark> CreateModelBenchmark(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float p50_latency_ms = 0.0f,
    float p90_latency_ms = 0.0f,
    float p99_latency_ms = 0.0f,
    float peak_memory_mb = 0.0f,
    float weight_memory_mb = 0.0f,
    float throughput_fps = 0.0f) {
  ModelBenchmarkBuilder builder_(_fbb);
  builder_.add_throughput_fps(throughput_fps);
  builder_.add_weight_memory_mb(weight_memory_mb);
  builder_.add_peak_memory_mb(peak_memory_mb);
  builder_.add_p99_latency_ms(p99_latency_ms);
  builder_.add_p90_latency_ms(p90_latency_ms);
  builder_.add_p50_latency_ms(p50_latency_ms);
  return builder_.Finish();
}

::flatbuffers::Offset<ModelBenchmark> CreateModelBenchmark(::flatbuffers::FlatBufferBuilder &_fbb, const ModelBenchmarkT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct AccuracyInfoT : public ::flatbuffers::NativeTable {
  typedef AccuracyInfo TableType;
  std::string dataset{};
  float top1_accuracy = 0.0f;
  float top5_accuracy = 0.0f;
  float mean_iou = 0.0f;
  float accuracy_drop = 0.0f;
};

struct AccuracyInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AccuracyInfoT NativeTableType;
  typedef AccuracyInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATASET = 4,
    VT_TOP1_ACCURACY = 6,
    VT_TOP5_ACCURACY = 8,
    VT_MEAN_IOU = 10,
    VT_ACCURACY_DROP = 12
  };
  const ::flatbuffers::String *dataset() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATASET);
  }
  float top1_accuracy() const {
    return GetField<float>(VT_TOP1_ACCURACY, 0.0f);
  }
  float top5_accuracy() const {
    return GetField<float>(VT_TOP5_ACCURACY, 0.0f);
  }
  float mean_iou() const {
    return GetField<float>(VT_MEAN_IOU, 0.0f);
  }
  float accuracy_drop() const {
    return GetField<float>(VT_ACCURACY_DROP, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATASET) &&
           verifier.VerifyString(dataset()) &&
           VerifyField<float>(verifier, VT_TOP1_ACCURACY, 4) &&
           VerifyField<float>(verifier, VT_TOP5_ACCURACY, 4) &&
           VerifyField<float>(verifier, VT_MEAN_IOU, 4) &&
           VerifyField<float>(verifier, VT_ACCURACY_DROP, 4) &&
           verifier.EndTable();
  }
  AccuracyInfoT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AccuracyInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<AccuracyInfo> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AccuracyInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AccuracyInfoBuilder {
  typedef AccuracyInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_dataset(::flatbuffers::Offset<::flatbuffers::String> dataset) {
    fbb_.AddOffset(AccuracyInfo::VT_DATASET, dataset);
  }
  void add_top1_accuracy(float top1_accuracy) {
    fbb_.AddElement<float>(AccuracyInfo::VT_TOP1_ACCURACY, top1_accuracy, 0.0f);
  }
  void add_top5_accuracy(float top5_accuracy) {
    fbb_.AddElement<float>(AccuracyInfo::VT_TOP5_ACCURACY, top5_accuracy, 0.0f);
  }
  void add_mean_iou(float mean_iou) {
    fbb_.AddElement<float>(AccuracyInfo::VT_MEAN_IOU, mean_iou, 0.0f);
  }
  void add_accuracy_drop(float accuracy_drop) {
    fbb_.AddElement<float>(AccuracyInfo::VT_ACCURACY_DROP, accuracy_drop, 0.0f);
  }
  explicit AccuracyInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AccuracyInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AccuracyInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AccuracyInfo> CreateAccuracyInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> dataset = 0,
    float top1_accuracy = 0.0f,
    float top5_accuracy = 0.0f,
    float mean_iou = 0.0f,
    float accuracy_drop = 0.0f) {
  AccuracyInfoBuilder builder_(_fbb);
  builder_.add_accuracy_drop(accuracy_drop);
  builder_.add_mean_iou(mean_iou);
  builder_.add_top5_accuracy(top5_accuracy);
  builder_.add_top1_accuracy(top1_accuracy);
  builder_.add_dataset(dataset);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AccuracyInfo> CreateAccuracyInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *dataset = nullptr,
    float top1_accuracy = 0.0f,
    float top5_accuracy = 0.0f,
    float mean_iou = 0.0f,
    float accuracy_drop = 0.0f) {
  auto dataset__ = dataset ? _fbb.CreateString(dataset) : 0;
  return qoocore::CreateAccuracyInfo(
      _fbb,
      dataset__,
      top1_accuracy,
      top5_accuracy,
      mean_iou,
      accuracy_drop);
}

::flatbuffers::Offset<AccuracyInfo> CreateAccuracyInfo(::flatbuffers::FlatBufferBuilder &_fbb, const AccuracyInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct QooModelT : public ::flatbuffers::NativeTable {
  typedef QooModel TableType;
  uint32_t version = 1;
  std::vector<uint8_t> magic{};
  uint32_t flags = 0;
  std::string model_name{};
  std::vector<std::unique_ptr<qoocore::TensorInfoT>> inputs{};
  std::vector<std::unique_ptr<qoocore::TensorInfoT>> outputs{};
  std::vector<std::unique_ptr<qoocore::BackendCompiledInfoT>> compiled_infos{};
  qoocore::BackendType target_backend = qoocore::BackendType_AUTO;
  std::unique_ptr<qoocore::ModelWeightsT> weights{};
  std::string config_yaml{};
  std::unique_ptr<qoocore::ModelMetadataT> metadata{};
  std::vector<uint8_t> content_checksum{};
  QooModelT() = default;
  QooModelT(const QooModelT &o);
  QooModelT(QooModelT&&) FLATBUFFERS_NOEXCEPT = default;
  QooModelT &operator=(QooModelT o) FLATBUFFERS_NOEXCEPT;
};

struct QooModel FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef QooModelT NativeTableType;
  typedef QooModelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_MAGIC = 6,
    VT_FLAGS = 8,
    VT_MODEL_NAME = 10,
    VT_INPUTS = 12,
    VT_OUTPUTS = 14,
    VT_COMPILED_INFOS = 16,
    VT_TARGET_BACKEND = 18,
    VT_WEIGHTS = 20,
    VT_CONFIG_YAML = 22,
    VT_METADATA = 24,
    VT_CONTENT_CHECKSUM = 26
  };
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 1);
  }
  const ::flatbuffers::Vector<uint8_t> *magic() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_MAGIC);
  }
  uint32_t flags() const {
    return GetField<uint32_t>(VT_FLAGS, 0);
  }
  const ::flatbuffers::String *model_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODEL_NAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<qoocore::TensorInfo>> *inputs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<qoocore::TensorInfo>> *>(VT_INPUTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<qoocore::TensorInfo>> *outputs() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<qoocore::TensorInfo>> *>(VT_OUTPUTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<qoocore::BackendCompiledInfo>> *compiled_infos() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<qoocore::BackendCompiledInfo>> *>(VT_COMPILED_INFOS);
  }
  qoocore::BackendType target_backend() const {
    return static_cast<qoocore::BackendType>(GetField<uint8_t>(VT_TARGET_BACKEND, 255));
  }
  const qoocore::ModelWeights *weights() const {
    return GetPointer<const qoocore::ModelWeights *>(VT_WEIGHTS);
  }
  const ::flatbuffers::String *config_yaml() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONFIG_YAML);
  }
  const qoocore::ModelMetadata *metadata() const {
    return GetPointer<const qoocore::ModelMetadata *>(VT_METADATA);
  }
  const ::flatbuffers::Vector<uint8_t> *content_checksum() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_CONTENT_CHECKSUM);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_MAGIC) &&
           verifier.VerifyVector(magic()) &&
           VerifyField<uint32_t>(verifier, VT_FLAGS, 4) &&
           VerifyOffsetRequired(verifier, VT_MODEL_NAME) &&
           verifier.VerifyString(model_name()) &&
           VerifyOffsetRequired(verifier, VT_INPUTS) &&
           verifier.VerifyVector(inputs()) &&
           verifier.VerifyVectorOfTables(inputs()) &&
           VerifyOffsetRequired(verifier, VT_OUTPUTS) &&
           verifier.VerifyVector(outputs()) &&
           verifier.VerifyVectorOfTables(outputs()) &&
           VerifyOffset(verifier, VT_COMPILED_INFOS) &&
           verifier.VerifyVector(compiled_infos()) &&
           verifier.VerifyVectorOfTables(compiled_infos()) &&
           VerifyField<uint8_t>(verifier, VT_TARGET_BACKEND, 1) &&
           VerifyOffset(verifier, VT_WEIGHTS) &&
           verifier.VerifyTable(weights()) &&
           VerifyOffset(verifier, VT_CONFIG_YAML) &&
           verifier.VerifyString(config_yaml()) &&
           VerifyOffset(verifier, VT_METADATA) &&
           verifier.VerifyTable(metadata()) &&
           VerifyOffset(verifier, VT_CONTENT_CHECKSUM) &&
           verifier.VerifyVector(content_checksum()) &&
           verifier.EndTable();
  }
  QooModelT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(QooModelT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<QooModel> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const QooModelT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct QooModelBuilder {
  typedef QooModel Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(QooModel::VT_VERSION, version, 1);
  }
  void add_magic(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> magic) {
    fbb_.AddOffset(QooModel::VT_MAGIC, magic);
  }
  void add_flags(uint32_t flags) {
    fbb_.AddElement<uint32_t>(QooModel::VT_FLAGS, flags, 0);
  }
  void add_model_name(::flatbuffers::Offset<::flatbuffers::String> model_name) {
    fbb_.AddOffset(QooModel::VT_MODEL_NAME, model_name);
  }
  void add_inputs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<qoocore::TensorInfo>>> inputs) {
    fbb_.AddOffset(QooModel::VT_INPUTS, inputs);
  }
  void add_outputs(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<qoocore::TensorInfo>>> outputs) {
    fbb_.AddOffset(QooModel::VT_OUTPUTS, outputs);
  }
  void add_compiled_infos(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<qoocore::BackendCompiledInfo>>> compiled_infos) {
    fbb_.AddOffset(QooModel::VT_COMPILED_INFOS, compiled_infos);
  }
  void add_target_backend(qoocore::BackendType target_backend) {
    fbb_.AddElement<uint8_t>(QooModel::VT_TARGET_BACKEND, static_cast<uint8_t>(target_backend), 255);
  }
  void add_weights(::flatbuffers::Offset<qoocore::ModelWeights> weights) {
    fbb_.AddOffset(QooModel::VT_WEIGHTS, weights);
  }
  void add_config_yaml(::flatbuffers::Offset<::flatbuffers::String> config_yaml) {
    fbb_.AddOffset(QooModel::VT_CONFIG_YAML, config_yaml);
  }
  void add_metadata(::flatbuffers::Offset<qoocore::ModelMetadata> metadata) {
    fbb_.AddOffset(QooModel::VT_METADATA, metadata);
  }
  void add_content_checksum(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> content_checksum) {
    fbb_.AddOffset(QooModel::VT_CONTENT_CHECKSUM, content_checksum);
  }
  explicit QooModelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<QooModel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<QooModel>(end);
    fbb_.Required(o, QooModel::VT_MODEL_NAME);
    fbb_.Required(o, QooModel::VT_INPUTS);
    fbb_.Required(o, QooModel::VT_OUTPUTS);
    return o;
  }
};

inline ::flatbuffers::Offset<QooModel> CreateQooModel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 1,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> magic = 0,
    uint32_t flags = 0,
    ::flatbuffers::Offset<::flatbuffers::String> model_name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<qoocore::TensorInfo>>> inputs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<qoocore::TensorInfo>>> outputs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<qoocore::BackendCompiledInfo>>> compiled_infos = 0,
    qoocore::BackendType target_backend = qoocore::BackendType_AUTO,
    ::flatbuffers::Offset<qoocore::ModelWeights> weights = 0,
    ::flatbuffers::Offset<::flatbuffers::String> config_yaml = 0,
    ::flatbuffers::Offset<qoocore::ModelMetadata> metadata = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> content_checksum = 0) {
  QooModelBuilder builder_(_fbb);
  builder_.add_content_checksum(content_checksum);
  builder_.add_metadata(metadata);
  builder_.add_config_yaml(config_yaml);
  builder_.add_weights(weights);
  builder_.add_compiled_infos(compiled_infos);
  builder_.add_outputs(outputs);
  builder_.add_inputs(inputs);
  builder_.add_model_name(model_name);
  builder_.add_flags(flags);
  builder_.add_magic(magic);
  builder_.add_version(version);
  builder_.add_target_backend(target_backend);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<QooModel> CreateQooModelDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 1,
    const std::vector<uint8_t> *magic = nullptr,
    uint32_t flags = 0,
    const char *model_name = nullptr,
    const std::vector<::flatbuffers::Offset<qoocore::TensorInfo>> *inputs = nullptr,
    const std::vector<::flatbuffers::Offset<qoocore::TensorInfo>> *outputs = nullptr,
    const std::vector<::flatbuffers::Offset<qoocore::BackendCompiledInfo>> *compiled_infos = nullptr,
    qoocore::BackendType target_backend = qoocore::BackendType_AUTO,
    ::flatbuffers::Offset<qoocore::ModelWeights> weights = 0,
    const char *config_yaml = nullptr,
    ::flatbuffers::Offset<qoocore::ModelMetadata> metadata = 0,
    const std::vector<uint8_t> *content_checksum = nullptr) {
  auto magic__ = magic ? _fbb.CreateVector<uint8_t>(*magic) : 0;
  auto model_name__ = model_name ? _fbb.CreateString(model_name) : 0;
  auto inputs__ = inputs ? _fbb.CreateVector<::flatbuffers::Offset<qoocore::TensorInfo>>(*inputs) : 0;
  auto outputs__ = outputs ? _fbb.CreateVector<::flatbuffers::Offset<qoocore::TensorInfo>>(*outputs) : 0;
  auto compiled_infos__ = compiled_infos ? _fbb.CreateVector<::flatbuffers::Offset<qoocore::BackendCompiledInfo>>(*compiled_infos) : 0;
  auto config_yaml__ = config_yaml ? _fbb.CreateString(config_yaml) : 0;
  auto content_checksum__ = content_checksum ? _fbb.CreateVector<uint8_t>(*content_checksum) : 0;
  return qoocore::CreateQooModel(
      _fbb,
      version,
      magic__,
      flags,
      model_name__,
      inputs__,
      outputs__,
      compiled_infos__,
      target_backend,
      weights,
      config_yaml__,
      metadata,
      content_checksum__);
}

::flatbuffers::Offset<QooModel> CreateQooModel(::flatbuffers::FlatBufferBuilder &_fbb, const QooModelT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const QuantizationInfoT &lhs, const QuantizationInfoT &rhs) {
  return
      (lhs.dtype == rhs.dtype) &&
      (lhs.scales == rhs.scales) &&
      (lhs.zero_points == rhs.zero_points) &&
      (lhs.per_channel == rhs.per_channel);
}

inline bool operator!=(const QuantizationInfoT &lhs, const QuantizationInfoT &rhs) {
    return !(lhs == rhs);
}


inline QuantizationInfoT *QuantizationInfo::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<QuantizationInfoT>(new QuantizationInfoT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void QuantizationInfo::UnPackTo(QuantizationInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = dtype(); _o->dtype = _e; }
  { auto _e = scales(); if (_e) { _o->scales.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->scales[_i] = _e->Get(_i); } } else { _o->scales.resize(0); } }
  { auto _e = zero_points(); if (_e) { _o->zero_points.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->zero_points[_i] = _e->Get(_i); } } else { _o->zero_points.resize(0); } }
  { auto _e = per_channel(); _o->per_channel = _e; }
}

inline ::flatbuffers::Offset<QuantizationInfo> QuantizationInfo::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const QuantizationInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateQuantizationInfo(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<QuantizationInfo> CreateQuantizationInfo(::flatbuffers::FlatBufferBuilder &_fbb, const QuantizationInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const QuantizationInfoT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _dtype = _o->dtype;
  auto _scales = _o->scales.size() ? _fbb.CreateVector(_o->scales) : 0;
  auto _zero_points = _o->zero_points.size() ? _fbb.CreateVector(_o->zero_points) : 0;
  auto _per_channel = _o->per_channel;
  return qoocore::CreateQuantizationInfo(
      _fbb,
      _dtype,
      _scales,
      _zero_points,
      _per_channel);
}


inline bool operator==(const TensorInfoT &lhs, const TensorInfoT &rhs) {
  return
      (lhs.name == rhs.name) &&
      (lhs.dtype == rhs.dtype) &&
      (lhs.layout == rhs.layout) &&
      (lhs.shape == rhs.shape) &&
      ((lhs.quant == rhs.quant) || (lhs.quant && rhs.quant && *lhs.quant == *rhs.quant)) &&
      (lhs.description == rhs.description);
}

inline bool operator!=(const TensorInfoT &lhs, const TensorInfoT &rhs) {
    return !(lhs == rhs);
}


inline TensorInfoT::TensorInfoT(const TensorInfoT &o)
      : name(o.name),
        dtype(o.dtype),
        layout(o.layout),
        shape(o.shape),
        quant((o.quant) ? new qoocore::QuantizationInfoT(*o.quant) : nullptr),
        description(o.description) {
}

inline TensorInfoT &TensorInfoT::operator=(TensorInfoT o) FLATBUFFERS_NOEXCEPT {
  std::swap(name, o.name);
  std::swap(dtype, o.dtype);
  std::swap(layout, o.layout);
  std::swap(shape, o.shape);
  std::swap(quant, o.quant);
  std::swap(description, o.description);
  return *this;
}

inline TensorInfoT *TensorInfo::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TensorInfoT>(new TensorInfoT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TensorInfo::UnPackTo(TensorInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = dtype(); _o->dtype = _e; }
  { auto _e = layout(); _o->layout = _e; }
  { auto _e = shape(); if (_e) { _o->shape.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->shape[_i] = _e->Get(_i); } } else { _o->shape.resize(0); } }
  { auto _e = quant(); if (_e) { if(_o->quant) { _e->UnPackTo(_o->quant.get(), _resolver); } else { _o->quant = std::unique_ptr<qoocore::QuantizationInfoT>(_e->UnPack(_resolver)); } } else if (_o->quant) { _o->quant.reset(); } }
  { auto _e = description(); if (_e) _o->description = _e->str(); }
}

inline ::flatbuffers::Offset<TensorInfo> TensorInfo::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TensorInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateTensorInfo(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TensorInfo> CreateTensorInfo(::flatbuffers::FlatBufferBuilder &_fbb, const TensorInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TensorInfoT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _dtype = _o->dtype;
  auto _layout = _o->layout;
  auto _shape = _o->shape.size() ? _fbb.CreateVector(_o->shape) : 0;
  auto _quant = _o->quant ? CreateQuantizationInfo(_fbb, _o->quant.get(), _rehasher) : 0;
  auto _description = _o->description.empty() ? 0 : _fbb.CreateString(_o->description);
  return qoocore::CreateTensorInfo(
      _fbb,
      _name,
      _dtype,
      _layout,
      _shape,
      _quant,
      _description);
}


inline bool operator==(const BackendCompiledInfoT &lhs, const BackendCompiledInfoT &rhs) {
  return
      (lhs.backend_type == rhs.backend_type) &&
      (lhs.compiled_data == rhs.compiled_data) &&
      (lhs.backend_config == rhs.backend_config) &&
      (lhs.estimated_latency_ms == rhs.estimated_latency_ms) &&
      (lhs.estimated_memory_mb == rhs.estimated_memory_mb);
}

inline bool operator!=(const BackendCompiledInfoT &lhs, const BackendCompiledInfoT &rhs) {
    return !(lhs == rhs);
}


inline BackendCompiledInfoT *BackendCompiledInfo::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BackendCompiledInfoT>(new BackendCompiledInfoT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BackendCompiledInfo::UnPackTo(BackendCompiledInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = backend_type(); _o->backend_type = _e; }
  { auto _e = compiled_data(); if (_e) { _o->compiled_data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->compiled_data.begin()); } }
  { auto _e = backend_config(); if (_e) _o->backend_config = _e->str(); }
  { auto _e = estimated_latency_ms(); _o->estimated_latency_ms = _e; }
  { auto _e = estimated_memory_mb(); _o->estimated_memory_mb = _e; }
}

inline ::flatbuffers::Offset<BackendCompiledInfo> BackendCompiledInfo::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BackendCompiledInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBackendCompiledInfo(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BackendCompiledInfo> CreateBackendCompiledInfo(::flatbuffers::FlatBufferBuilder &_fbb, const BackendCompiledInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BackendCompiledInfoT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _backend_type = _o->backend_type;
  auto _compiled_data = _fbb.CreateVector(_o->compiled_data);
  auto _backend_config = _o->backend_config.empty() ? 0 : _fbb.CreateString(_o->backend_config);
  auto _estimated_latency_ms = _o->estimated_latency_ms;
  auto _estimated_memory_mb = _o->estimated_memory_mb;
  return qoocore::CreateBackendCompiledInfo(
      _fbb,
      _backend_type,
      _compiled_data,
      _backend_config,
      _estimated_latency_ms,
      _estimated_memory_mb);
}


inline bool operator==(const ModelWeightsT &lhs, const ModelWeightsT &rhs) {
  return
      (lhs.weights_data == rhs.weights_data) &&
      (lhs.weight_size == rhs.weight_size) &&
      (lhs.weight_tensors.size() == rhs.weight_tensors.size() && std::equal(lhs.weight_tensors.cbegin(), lhs.weight_tensors.cend(), rhs.weight_tensors.cbegin(), [](std::unique_ptr<qoocore::TensorInfoT> const &a, std::unique_ptr<qoocore::TensorInfoT> const &b) { return (a == b) || (a && b && *a == *b); }));
}

inline bool operator!=(const ModelWeightsT &lhs, const ModelWeightsT &rhs) {
    return !(lhs == rhs);
}


inline ModelWeightsT::ModelWeightsT(const ModelWeightsT &o)
      : weights_data(o.weights_data),
        weight_size(o.weight_size) {
  weight_tensors.reserve(o.weight_tensors.size());
  for (const auto &weight_tensors_ : o.weight_tensors) { weight_tensors.emplace_back((weight_tensors_) ? new qoocore::TensorInfoT(*weight_tensors_) : nullptr); }
}

inline ModelWeightsT &ModelWeightsT::operator=(ModelWeightsT o) FLATBUFFERS_NOEXCEPT {
  std::swap(weights_data, o.weights_data);
  std::swap(weight_size, o.weight_size);
  std::swap(weight_tensors, o.weight_tensors);
  return *this;
}

inline ModelWeightsT *ModelWeights::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ModelWeightsT>(new ModelWeightsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ModelWeights::UnPackTo(ModelWeightsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = weights_data(); if (_e) { _o->weights_data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->weights_data.begin()); } }
  { auto _e = weight_size(); _o->weight_size = _e; }
  { auto _e = weight_tensors(); if (_e) { _o->weight_tensors.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->weight_tensors[_i]) { _e->Get(_i)->UnPackTo(_o->weight_tensors[_i].get(), _resolver); } else { _o->weight_tensors[_i] = std::unique_ptr<qoocore::TensorInfoT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->weight_tensors.resize(0); } }
}

inline ::flatbuffers::Offset<ModelWeights> ModelWeights::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ModelWeightsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateModelWeights(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ModelWeights> CreateModelWeights(::flatbuffers::FlatBufferBuilder &_fbb, const ModelWeightsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ModelWeightsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _weights_data = _fbb.CreateVector(_o->weights_data);
  auto _weight_size = _o->weight_size;
  auto _weight_tensors = _o->weight_tensors.size() ? _fbb.CreateVector<::flatbuffers::Offset<qoocore::TensorInfo>> (_o->weight_tensors.size(), [](size_t i, _VectorArgs *__va) { return CreateTensorInfo(*__va->__fbb, __va->__o->weight_tensors[i].get(), __va->__rehasher); }, &_va ) : 0;
  return qoocore::CreateModelWeights(
      _fbb,
      _weights_data,
      _weight_size,
      _weight_tensors);
}


inline bool operator==(const ModelConfigT &lhs, const ModelConfigT &rhs) {
  return
      (lhs.optimization_level == rhs.optimization_level) &&
      (lhs.quant_scheme == rhs.quant_scheme) &&
      (lhs.calibration_samples == rhs.calibration_samples) &&
      (lhs.target_chip == rhs.target_chip) &&
      (lhs.support_dynamic_batch == rhs.support_dynamic_batch) &&
      (lhs.max_batch_size == rhs.max_batch_size);
}

inline bool operator!=(const ModelConfigT &lhs, const ModelConfigT &rhs) {
    return !(lhs == rhs);
}


inline ModelConfigT *ModelConfig::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ModelConfigT>(new ModelConfigT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ModelConfig::UnPackTo(ModelConfigT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = optimization_level(); _o->optimization_level = _e; }
  { auto _e = quant_scheme(); if (_e) _o->quant_scheme = _e->str(); }
  { auto _e = calibration_samples(); _o->calibration_samples = _e; }
  { auto _e = target_chip(); if (_e) _o->target_chip = _e->str(); }
  { auto _e = support_dynamic_batch(); _o->support_dynamic_batch = _e; }
  { auto _e = max_batch_size(); _o->max_batch_size = _e; }
}

inline ::flatbuffers::Offset<ModelConfig> ModelConfig::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ModelConfigT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateModelConfig(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ModelConfig> CreateModelConfig(::flatbuffers::FlatBufferBuilder &_fbb, const ModelConfigT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ModelConfigT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _optimization_level = _o->optimization_level;
  auto _quant_scheme = _o->quant_scheme.empty() ? 0 : _fbb.CreateString(_o->quant_scheme);
  auto _calibration_samples = _o->calibration_samples;
  auto _target_chip = _o->target_chip.empty() ? 0 : _fbb.CreateString(_o->target_chip);
  auto _support_dynamic_batch = _o->support_dynamic_batch;
  auto _max_batch_size = _o->max_batch_size;
  return qoocore::CreateModelConfig(
      _fbb,
      _optimization_level,
      _quant_scheme,
      _calibration_samples,
      _target_chip,
      _support_dynamic_batch,
      _max_batch_size);
}


inline bool operator==(const ModelMetadataT &lhs, const ModelMetadataT &rhs) {
  return
      (lhs.source_format == rhs.source_format) &&
      (lhs.source_path == rhs.source_path) &&
      (lhs.source_opset == rhs.source_opset) &&
      (lhs.export_date == rhs.export_date) &&
      (lhs.compiler_version == rhs.compiler_version) &&
      (lhs.compile_date == rhs.compile_date) &&
      (lhs.compile_host == rhs.compile_host) &&
      ((lhs.benchmark == rhs.benchmark) || (lhs.benchmark && rhs.benchmark && *lhs.benchmark == *rhs.benchmark)) &&
      ((lhs.accuracy == rhs.accuracy) || (lhs.accuracy && rhs.accuracy && *lhs.accuracy == *rhs.accuracy)) &&
      (lhs.extra == rhs.extra);
}

inline bool operator!=(const ModelMetadataT &lhs, const ModelMetadataT &rhs) {
    return !(lhs == rhs);
}


inline ModelMetadataT::ModelMetadataT(const ModelMetadataT &o)
      : source_format(o.source_format),
        source_path(o.source_path),
        source_opset(o.source_opset),
        export_date(o.export_date),
        compiler_version(o.compiler_version),
        compile_date(o.compile_date),
        compile_host(o.compile_host),
        benchmark((o.benchmark) ? new qoocore::ModelBenchmarkT(*o.benchmark) : nullptr),
        accuracy((o.accuracy) ? new qoocore::AccuracyInfoT(*o.accuracy) : nullptr),
        extra(o.extra) {
}

inline ModelMetadataT &ModelMetadataT::operator=(ModelMetadataT o) FLATBUFFERS_NOEXCEPT {
  std::swap(source_format, o.source_format);
  std::swap(source_path, o.source_path);
  std::swap(source_opset, o.source_opset);
  std::swap(export_date, o.export_date);
  std::swap(compiler_version, o.compiler_version);
  std::swap(compile_date, o.compile_date);
  std::swap(compile_host, o.compile_host);
  std::swap(benchmark, o.benchmark);
  std::swap(accuracy, o.accuracy);
  std::swap(extra, o.extra);
  return *this;
}

inline ModelMetadataT *ModelMetadata::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ModelMetadataT>(new ModelMetadataT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ModelMetadata::UnPackTo(ModelMetadataT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = source_format(); if (_e) _o->source_format = _e->str(); }
  { auto _e = source_path(); if (_e) _o->source_path = _e->str(); }
  { auto _e = source_opset(); _o->source_opset = _e; }
  { auto _e = export_date(); if (_e) _o->export_date = _e->str(); }
  { auto _e = compiler_version(); if (_e) _o->compiler_version = _e->str(); }
  { auto _e = compile_date(); if (_e) _o->compile_date = _e->str(); }
  { auto _e = compile_host(); if (_e) _o->compile_host = _e->str(); }
  { auto _e = benchmark(); if (_e) { if(_o->benchmark) { _e->UnPackTo(_o->benchmark.get(), _resolver); } else { _o->benchmark = std::unique_ptr<qoocore::ModelBenchmarkT>(_e->UnPack(_resolver)); } } else if (_o->benchmark) { _o->benchmark.reset(); } }
  { auto _e = accuracy(); if (_e) { if(_o->accuracy) { _e->UnPackTo(_o->accuracy.get(), _resolver); } else { _o->accuracy = std::unique_ptr<qoocore::AccuracyInfoT>(_e->UnPack(_resolver)); } } else if (_o->accuracy) { _o->accuracy.reset(); } }
  { auto _e = extra(); if (_e) _o->extra = _e->str(); }
}

inline ::flatbuffers::Offset<ModelMetadata> ModelMetadata::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ModelMetadataT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateModelMetadata(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ModelMetadata> CreateModelMetadata(::flatbuffers::FlatBufferBuilder &_fbb, const ModelMetadataT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ModelMetadataT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _source_format = _o->source_format.empty() ? 0 : _fbb.CreateString(_o->source_format);
  auto _source_path = _o->source_path.empty() ? 0 : _fbb.CreateString(_o->source_path);
  auto _source_opset = _o->source_opset;
  auto _export_date = _o->export_date.empty() ? 0 : _fbb.CreateString(_o->export_date);
  auto _compiler_version = _o->compiler_version.empty() ? 0 : _fbb.CreateString(_o->compiler_version);
  auto _compile_date = _o->compile_date.empty() ? 0 : _fbb.CreateString(_o->compile_date);
  auto _compile_host = _o->compile_host.empty() ? 0 : _fbb.CreateString(_o->compile_host);
  auto _benchmark = _o->benchmark ? CreateModelBenchmark(_fbb, _o->benchmark.get(), _rehasher) : 0;
  auto _accuracy = _o->accuracy ? CreateAccuracyInfo(_fbb, _o->accuracy.get(), _rehasher) : 0;
  auto _extra = _o->extra.empty() ? 0 : _fbb.CreateString(_o->extra);
  return qoocore::CreateModelMetadata(
      _fbb,
      _source_format,
      _source_path,
      _source_opset,
      _export_date,
      _compiler_version,
      _compile_date,
      _compile_host,
      _benchmark,
      _accuracy,
      _extra);
}


inline bool operator==(const ModelBenchmarkT &lhs, const ModelBenchmarkT &rhs) {
  return
      (lhs.p50_latency_ms == rhs.p50_latency_ms) &&
      (lhs.p90_latency_ms == rhs.p90_latency_ms) &&
      (lhs.p99_latency_ms == rhs.p99_latency_ms) &&
      (lhs.peak_memory_mb == rhs.peak_memory_mb) &&
      (lhs.weight_memory_mb == rhs.weight_memory_mb) &&
      (lhs.throughput_fps == rhs.throughput_fps);
}

inline bool operator!=(const ModelBenchmarkT &lhs, const ModelBenchmarkT &rhs) {
    return !(lhs == rhs);
}


inline ModelBenchmarkT *ModelBenchmark::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ModelBenchmarkT>(new ModelBenchmarkT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ModelBenchmark::UnPackTo(ModelBenchmarkT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = p50_latency_ms(); _o->p50_latency_ms = _e; }
  { auto _e = p90_latency_ms(); _o->p90_latency_ms = _e; }
  { auto _e = p99_latency_ms(); _o->p99_latency_ms = _e; }
  { auto _e = peak_memory_mb(); _o->peak_memory_mb = _e; }
  { auto _e = weight_memory_mb(); _o->weight_memory_mb = _e; }
  { auto _e = throughput_fps(); _o->throughput_fps = _e; }
}

inline ::flatbuffers::Offset<ModelBenchmark> ModelBenchmark::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ModelBenchmarkT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateModelBenchmark(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ModelBenchmark> CreateModelBenchmark(::flatbuffers::FlatBufferBuilder &_fbb, const ModelBenchmarkT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ModelBenchmarkT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _p50_latency_ms = _o->p50_latency_ms;
  auto _p90_latency_ms = _o->p90_latency_ms;
  auto _p99_latency_ms = _o->p99_latency_ms;
  auto _peak_memory_mb = _o->peak_memory_mb;
  auto _weight_memory_mb = _o->weight_memory_mb;
  auto _throughput_fps = _o->throughput_fps;
  return qoocore::CreateModelBenchmark(
      _fbb,
      _p50_latency_ms,
      _p90_latency_ms,
      _p99_latency_ms,
      _peak_memory_mb,
      _weight_memory_mb,
      _throughput_fps);
}


inline bool operator==(const AccuracyInfoT &lhs, const AccuracyInfoT &rhs) {
  return
      (lhs.dataset == rhs.dataset) &&
      (lhs.top1_accuracy == rhs.top1_accuracy) &&
      (lhs.top5_accuracy == rhs.top5_accuracy) &&
      (lhs.mean_iou == rhs.mean_iou) &&
      (lhs.accuracy_drop == rhs.accuracy_drop);
}

inline bool operator!=(const AccuracyInfoT &lhs, const AccuracyInfoT &rhs) {
    return !(lhs == rhs);
}


inline AccuracyInfoT *AccuracyInfo::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<AccuracyInfoT>(new AccuracyInfoT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AccuracyInfo::UnPackTo(AccuracyInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = dataset(); if (_e) _o->dataset = _e->str(); }
  { auto _e = top1_accuracy(); _o->top1_accuracy = _e; }
  { auto _e = top5_accuracy(); _o->top5_accuracy = _e; }
  { auto _e = mean_iou(); _o->mean_iou = _e; }
  { auto _e = accuracy_drop(); _o->accuracy_drop = _e; }
}

inline ::flatbuffers::Offset<AccuracyInfo> AccuracyInfo::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const AccuracyInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateAccuracyInfo(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<AccuracyInfo> CreateAccuracyInfo(::flatbuffers::FlatBufferBuilder &_fbb, const AccuracyInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const AccuracyInfoT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _dataset = _o->dataset.empty() ? 0 : _fbb.CreateString(_o->dataset);
  auto _top1_accuracy = _o->top1_accuracy;
  auto _top5_accuracy = _o->top5_accuracy;
  auto _mean_iou = _o->mean_iou;
  auto _accuracy_drop = _o->accuracy_drop;
  return qoocore::CreateAccuracyInfo(
      _fbb,
      _dataset,
      _top1_accuracy,
      _top5_accuracy,
      _mean_iou,
      _accuracy_drop);
}


inline bool operator==(const QooModelT &lhs, const QooModelT &rhs) {
  return
      (lhs.version == rhs.version) &&
      (lhs.magic == rhs.magic) &&
      (lhs.flags == rhs.flags) &&
      (lhs.model_name == rhs.model_name) &&
      (lhs.inputs.size() == rhs.inputs.size() && std::equal(lhs.inputs.cbegin(), lhs.inputs.cend(), rhs.inputs.cbegin(), [](std::unique_ptr<qoocore::TensorInfoT> const &a, std::unique_ptr<qoocore::TensorInfoT> const &b) { return (a == b) || (a && b && *a == *b); })) &&
      (lhs.outputs.size() == rhs.outputs.size() && std::equal(lhs.outputs.cbegin(), lhs.outputs.cend(), rhs.outputs.cbegin(), [](std::unique_ptr<qoocore::TensorInfoT> const &a, std::unique_ptr<qoocore::TensorInfoT> const &b) { return (a == b) || (a && b && *a == *b); })) &&
      (lhs.compiled_infos.size() == rhs.compiled_infos.size() && std::equal(lhs.compiled_infos.cbegin(), lhs.compiled_infos.cend(), rhs.compiled_infos.cbegin(), [](std::unique_ptr<qoocore::BackendCompiledInfoT> const &a, std::unique_ptr<qoocore::BackendCompiledInfoT> const &b) { return (a == b) || (a && b && *a == *b); })) &&
      (lhs.target_backend == rhs.target_backend) &&
      ((lhs.weights == rhs.weights) || (lhs.weights && rhs.weights && *lhs.weights == *rhs.weights)) &&
      (lhs.config_yaml == rhs.config_yaml) &&
      ((lhs.metadata == rhs.metadata) || (lhs.metadata && rhs.metadata && *lhs.metadata == *rhs.metadata)) &&
      (lhs.content_checksum == rhs.content_checksum);
}

inline bool operator!=(const QooModelT &lhs, const QooModelT &rhs) {
    return !(lhs == rhs);
}


inline QooModelT::QooModelT(const QooModelT &o)
      : version(o.version),
        magic(o.magic),
        flags(o.flags),
        model_name(o.model_name),
        target_backend(o.target_backend),
        weights((o.weights) ? new qoocore::ModelWeightsT(*o.weights) : nullptr),
        config_yaml(o.config_yaml),
        metadata((o.metadata) ? new qoocore::ModelMetadataT(*o.metadata) : nullptr),
        content_checksum(o.content_checksum) {
  inputs.reserve(o.inputs.size());
  for (const auto &inputs_ : o.inputs) { inputs.emplace_back((inputs_) ? new qoocore::TensorInfoT(*inputs_) : nullptr); }
  outputs.reserve(o.outputs.size());
  for (const auto &outputs_ : o.outputs) { outputs.emplace_back((outputs_) ? new qoocore::TensorInfoT(*outputs_) : nullptr); }
  compiled_infos.reserve(o.compiled_infos.size());
  for (const auto &compiled_infos_ : o.compiled_infos) { compiled_infos.emplace_back((compiled_infos_) ? new qoocore::BackendCompiledInfoT(*compiled_infos_) : nullptr); }
}

inline QooModelT &QooModelT::operator=(QooModelT o) FLATBUFFERS_NOEXCEPT {
  std::swap(version, o.version);
  std::swap(magic, o.magic);
  std::swap(flags, o.flags);
  std::swap(model_name, o.model_name);
  std::swap(inputs, o.inputs);
  std::swap(outputs, o.outputs);
  std::swap(compiled_infos, o.compiled_infos);
  std::swap(target_backend, o.target_backend);
  std::swap(weights, o.weights);
  std::swap(config_yaml, o.config_yaml);
  std::swap(metadata, o.metadata);
  std::swap(content_checksum, o.content_checksum);
  return *this;
}

inline QooModelT *QooModel::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<QooModelT>(new QooModelT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void QooModel::UnPackTo(QooModelT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = version(); _o->version = _e; }
  { auto _e = magic(); if (_e) { _o->magic.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->magic.begin()); } }
  { auto _e = flags(); _o->flags = _e; }
  { auto _e = model_name(); if (_e) _o->model_name = _e->str(); }
  { auto _e = inputs(); if (_e) { _o->inputs.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->inputs[_i]) { _e->Get(_i)->UnPackTo(_o->inputs[_i].get(), _resolver); } else { _o->inputs[_i] = std::unique_ptr<qoocore::TensorInfoT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->inputs.resize(0); } }
  { auto _e = outputs(); if (_e) { _o->outputs.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->outputs[_i]) { _e->Get(_i)->UnPackTo(_o->outputs[_i].get(), _resolver); } else { _o->outputs[_i] = std::unique_ptr<qoocore::TensorInfoT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->outputs.resize(0); } }
  { auto _e = compiled_infos(); if (_e) { _o->compiled_infos.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->compiled_infos[_i]) { _e->Get(_i)->UnPackTo(_o->compiled_infos[_i].get(), _resolver); } else { _o->compiled_infos[_i] = std::unique_ptr<qoocore::BackendCompiledInfoT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->compiled_infos.resize(0); } }
  { auto _e = target_backend(); _o->target_backend = _e; }
  { auto _e = weights(); if (_e) { if(_o->weights) { _e->UnPackTo(_o->weights.get(), _resolver); } else { _o->weights = std::unique_ptr<qoocore::ModelWeightsT>(_e->UnPack(_resolver)); } } else if (_o->weights) { _o->weights.reset(); } }
  { auto _e = config_yaml(); if (_e) _o->config_yaml = _e->str(); }
  { auto _e = metadata(); if (_e) { if(_o->metadata) { _e->UnPackTo(_o->metadata.get(), _resolver); } else { _o->metadata = std::unique_ptr<qoocore::ModelMetadataT>(_e->UnPack(_resolver)); } } else if (_o->metadata) { _o->metadata.reset(); } }
  { auto _e = content_checksum(); if (_e) { _o->content_checksum.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->content_checksum.begin()); } }
}

inline ::flatbuffers::Offset<QooModel> QooModel::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const QooModelT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateQooModel(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<QooModel> CreateQooModel(::flatbuffers::FlatBufferBuilder &_fbb, const QooModelT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const QooModelT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _version = _o->version;
  auto _magic = _o->magic.size() ? _fbb.CreateVector(_o->magic) : 0;
  auto _flags = _o->flags;
  auto _model_name = _fbb.CreateString(_o->model_name);
  auto _inputs = _fbb.CreateVector<::flatbuffers::Offset<qoocore::TensorInfo>> (_o->inputs.size(), [](size_t i, _VectorArgs *__va) { return CreateTensorInfo(*__va->__fbb, __va->__o->inputs[i].get(), __va->__rehasher); }, &_va );
  auto _outputs = _fbb.CreateVector<::flatbuffers::Offset<qoocore::TensorInfo>> (_o->outputs.size(), [](size_t i, _VectorArgs *__va) { return CreateTensorInfo(*__va->__fbb, __va->__o->outputs[i].get(), __va->__rehasher); }, &_va );
  auto _compiled_infos = _o->compiled_infos.size() ? _fbb.CreateVector<::flatbuffers::Offset<qoocore::BackendCompiledInfo>> (_o->compiled_infos.size(), [](size_t i, _VectorArgs *__va) { return CreateBackendCompiledInfo(*__va->__fbb, __va->__o->compiled_infos[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _target_backend = _o->target_backend;
  auto _weights = _o->weights ? CreateModelWeights(_fbb, _o->weights.get(), _rehasher) : 0;
  auto _config_yaml = _o->config_yaml.empty() ? 0 : _fbb.CreateString(_o->config_yaml);
  auto _metadata = _o->metadata ? CreateModelMetadata(_fbb, _o->metadata.get(), _rehasher) : 0;
  auto _content_checksum = _o->content_checksum.size() ? _fbb.CreateVector(_o->content_checksum) : 0;
  return qoocore::CreateQooModel(
      _fbb,
      _version,
      _magic,
      _flags,
      _model_name,
      _inputs,
      _outputs,
      _compiled_infos,
      _target_backend,
      _weights,
      _config_yaml,
      _metadata,
      _content_checksum);
}

inline const qoocore::QooModel *GetQooModel(const void *buf) {
  return ::flatbuffers::GetRoot<qoocore::QooModel>(buf);
}

inline const qoocore::QooModel *GetSizePrefixedQooModel(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<qoocore::QooModel>(buf);
}

inline const char *QooModelIdentifier() {
  return "QOO1";
}

inline bool QooModelBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, QooModelIdentifier());
}

inline bool SizePrefixedQooModelBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, QooModelIdentifier(), true);
}

inline bool VerifyQooModelBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<qoocore::QooModel>(QooModelIdentifier());
}

inline bool VerifySizePrefixedQooModelBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<qoocore::QooModel>(QooModelIdentifier());
}

inline const char *QooModelExtension() {
  return "qoomodel";
}

inline void FinishQooModelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<qoocore::QooModel> root) {
  fbb.Finish(root, QooModelIdentifier());
}

inline void FinishSizePrefixedQooModelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<qoocore::QooModel> root) {
  fbb.FinishSizePrefixed(root, QooModelIdentifier());
}

inline std::unique_ptr<qoocore::QooModelT> UnPackQooModel(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<qoocore::QooModelT>(GetQooModel(buf)->UnPack(res));
}

inline std::unique_ptr<qoocore::QooModelT> UnPackSizePrefixedQooModel(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<qoocore::QooModelT>(GetSizePrefixedQooModel(buf)->UnPack(res));
}

}  // namespace qoocore

#endif  // FLATBUFFERS_GENERATED_QOOMODEL_QOOCORE_H_
