# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain_os/safety/types.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'brain_os/safety/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from brain_os.common import types_pb2 as brain__os_dot_common_dot_types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x62rain_os/safety/types.proto\x12\x0f\x62rain_os.safety\x1a\x1b\x62rain_os/common/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x01\n\x0bSafetyAlarm\x12\x10\n\x08\x61larm_id\x18\x01 \x01(\t\x12*\n\x05level\x18\x02 \x01(\x0e\x32\x1b.brain_os.safety.AlarmLevel\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12*\n\x08location\x18\x06 \x01(\x0b\x32\x18.brain_os.common.Vector3\x12\x12\n\nauto_clear\x18\x07 \x01(\x08\"\xf4\x01\n\x0eSafetySnapshot\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Header\x12\x10\n\x08robot_id\x18\x02 \x01(\t\x12+\n\x05state\x18\x03 \x01(\x0e\x32\x1c.brain_os.safety.SafetyState\x12\x33\n\ractive_alarms\x18\x04 \x03(\x0b\x32\x1c.brain_os.safety.SafetyAlarm\x12\x12\n\njoint_load\x18\x05 \x03(\x02\x12\x19\n\x11min_obstacle_dist\x18\x06 \x01(\x02\x12\x16\n\x0evelocity_scale\x18\x07 \x01(\x02*`\n\nAlarmLevel\x12\x11\n\rALARM_S3_INFO\x10\x00\x12\x14\n\x10\x41LARM_S2_WARNING\x10\x01\x12\x12\n\x0e\x41LARM_S1_ERROR\x10\x02\x12\x15\n\x11\x41LARM_S0_CRITICAL\x10\x03*S\n\x0bSafetyState\x12\x0f\n\x0bSAFE_NORMAL\x10\x00\x12\x10\n\x0cSAFE_REDUCED\x10\x01\x12\x0f\n\x0bSAFE_PAUSED\x10\x02\x12\x10\n\x0cSAFE_STOPPED\x10\x03\x42\x31Z/github.com/brain-os/brain_proto/brain_os/safetyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_os.safety.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/brain-os/brain_proto/brain_os/safety'
  _globals['_ALARMLEVEL']._serialized_start=579
  _globals['_ALARMLEVEL']._serialized_end=675
  _globals['_SAFETYSTATE']._serialized_start=677
  _globals['_SAFETYSTATE']._serialized_end=760
  _globals['_SAFETYALARM']._serialized_start=111
  _globals['_SAFETYALARM']._serialized_end=330
  _globals['_SAFETYSNAPSHOT']._serialized_start=333
  _globals['_SAFETYSNAPSHOT']._serialized_end=577
# @@protoc_insertion_point(module_scope)
