# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from brain_os.decision import service_pb2 as brain__os_dot_decision_dot_service__pb2
from brain_os.decision import types_pb2 as brain__os_dot_decision_dot_types__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in brain_os/decision/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DecisionServiceStub:
    """─────────────────────────────────────────────
    DecisionService — 决策服务 gRPC 接口
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutePlan = channel.unary_unary(
                '/brain_os.decision.DecisionService/ExecutePlan',
                request_serializer=brain__os_dot_decision_dot_service__pb2.ExecutePlanRequest.SerializeToString,
                response_deserializer=brain__os_dot_decision_dot_service__pb2.ExecutePlanResponse.FromString,
                _registered_method=True)
        self.GenerateTrajectories = channel.unary_unary(
                '/brain_os.decision.DecisionService/GenerateTrajectories',
                request_serializer=brain__os_dot_decision_dot_service__pb2.GenerateTrajectoriesRequest.SerializeToString,
                response_deserializer=brain__os_dot_decision_dot_service__pb2.GenerateTrajectoriesResponse.FromString,
                _registered_method=True)
        self.SelectTrajectory = channel.unary_unary(
                '/brain_os.decision.DecisionService/SelectTrajectory',
                request_serializer=brain__os_dot_decision_dot_service__pb2.SelectTrajectoryRequest.SerializeToString,
                response_deserializer=brain__os_dot_decision_dot_service__pb2.SelectTrajectoryResponse.FromString,
                _registered_method=True)
        self.CancelPlan = channel.unary_unary(
                '/brain_os.decision.DecisionService/CancelPlan',
                request_serializer=brain__os_dot_decision_dot_service__pb2.CancelPlanRequest.SerializeToString,
                response_deserializer=brain__os_dot_decision_dot_service__pb2.CancelPlanResponse.FromString,
                _registered_method=True)
        self.StreamPlanStatus = channel.unary_stream(
                '/brain_os.decision.DecisionService/StreamPlanStatus',
                request_serializer=brain__os_dot_decision_dot_service__pb2.StreamPlanStatusRequest.SerializeToString,
                response_deserializer=brain__os_dot_decision_dot_types__pb2.PlanStatus.FromString,
                _registered_method=True)


class DecisionServiceServicer:
    """─────────────────────────────────────────────
    DecisionService — 决策服务 gRPC 接口
    ─────────────────────────────────────────────

    """

    def ExecutePlan(self, request, context):
        """执行行为树（开始规划 + 执行）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTrajectories(self, request, context):
        """生成多条候选轨迹
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectTrajectory(self, request, context):
        """HITL：提交人类选择的轨迹
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelPlan(self, request, context):
        """取消当前规划
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPlanStatus(self, request, context):
        """流式获取规划状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecutePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePlan,
                    request_deserializer=brain__os_dot_decision_dot_service__pb2.ExecutePlanRequest.FromString,
                    response_serializer=brain__os_dot_decision_dot_service__pb2.ExecutePlanResponse.SerializeToString,
            ),
            'GenerateTrajectories': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTrajectories,
                    request_deserializer=brain__os_dot_decision_dot_service__pb2.GenerateTrajectoriesRequest.FromString,
                    response_serializer=brain__os_dot_decision_dot_service__pb2.GenerateTrajectoriesResponse.SerializeToString,
            ),
            'SelectTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectTrajectory,
                    request_deserializer=brain__os_dot_decision_dot_service__pb2.SelectTrajectoryRequest.FromString,
                    response_serializer=brain__os_dot_decision_dot_service__pb2.SelectTrajectoryResponse.SerializeToString,
            ),
            'CancelPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelPlan,
                    request_deserializer=brain__os_dot_decision_dot_service__pb2.CancelPlanRequest.FromString,
                    response_serializer=brain__os_dot_decision_dot_service__pb2.CancelPlanResponse.SerializeToString,
            ),
            'StreamPlanStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPlanStatus,
                    request_deserializer=brain__os_dot_decision_dot_service__pb2.StreamPlanStatusRequest.FromString,
                    response_serializer=brain__os_dot_decision_dot_types__pb2.PlanStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brain_os.decision.DecisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brain_os.decision.DecisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DecisionService:
    """─────────────────────────────────────────────
    DecisionService — 决策服务 gRPC 接口
    ─────────────────────────────────────────────

    """

    @staticmethod
    def ExecutePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.decision.DecisionService/ExecutePlan',
            brain__os_dot_decision_dot_service__pb2.ExecutePlanRequest.SerializeToString,
            brain__os_dot_decision_dot_service__pb2.ExecutePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTrajectories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.decision.DecisionService/GenerateTrajectories',
            brain__os_dot_decision_dot_service__pb2.GenerateTrajectoriesRequest.SerializeToString,
            brain__os_dot_decision_dot_service__pb2.GenerateTrajectoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.decision.DecisionService/SelectTrajectory',
            brain__os_dot_decision_dot_service__pb2.SelectTrajectoryRequest.SerializeToString,
            brain__os_dot_decision_dot_service__pb2.SelectTrajectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.decision.DecisionService/CancelPlan',
            brain__os_dot_decision_dot_service__pb2.CancelPlanRequest.SerializeToString,
            brain__os_dot_decision_dot_service__pb2.CancelPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPlanStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/brain_os.decision.DecisionService/StreamPlanStatus',
            brain__os_dot_decision_dot_service__pb2.StreamPlanStatusRequest.SerializeToString,
            brain__os_dot_decision_dot_types__pb2.PlanStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
