# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain_os/control/service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'brain_os/control/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from brain_os.control import types_pb2 as brain__os_dot_control_dot_types__pb2
from brain_os.common import types_pb2 as brain__os_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x62rain_os/control/service.proto\x12\x10\x62rain_os.control\x1a\x1c\x62rain_os/control/types.proto\x1a\x1b\x62rain_os/common/types.proto\"M\n\x18\x45xecuteTrajectoryRequest\x12\x31\n\x07\x63ommand\x18\x01 \x01(\x0b\x32 .brain_os.control.ControlCommand\"q\n\x16GripperControlResponse\x12\'\n\x06status\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Status\x12.\n\x05state\x18\x02 \x01(\x0b\x32\x1f.brain_os.control.GripperStatus\"(\n\x14GetJointStateRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\"m\n\x15GetJointStateResponse\x12\'\n\x06status\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Status\x12+\n\x05state\x18\x02 \x01(\x0b\x32\x1c.brain_os.control.JointState\"G\n\x14\x45mergencyStopRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\r\"V\n\x15\x45mergencyStopResponse\x12\'\n\x06status\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Status\x12\x14\n\x0cstop_time_ns\x18\x02 \x01(\x04\"@\n\x13ResumeMotionRequest\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x17\n\x0frequire_confirm\x18\x02 \x01(\x08\"?\n\x14ResumeMotionResponse\x12\'\n\x06status\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Status2\xf9\x03\n\x0e\x43ontrolService\x12\x66\n\x11\x45xecuteTrajectory\x12*.brain_os.control.ExecuteTrajectoryRequest\x1a#.brain_os.control.ExecutionFeedback0\x01\x12\\\n\x0e\x43ontrolGripper\x12 .brain_os.control.GripperCommand\x1a(.brain_os.control.GripperControlResponse\x12`\n\rGetJointState\x12&.brain_os.control.GetJointStateRequest\x1a\'.brain_os.control.GetJointStateResponse\x12`\n\rEmergencyStop\x12&.brain_os.control.EmergencyStopRequest\x1a\'.brain_os.control.EmergencyStopResponse\x12]\n\x0cResumeMotion\x12%.brain_os.control.ResumeMotionRequest\x1a&.brain_os.control.ResumeMotionResponseB2Z0github.com/brain-os/brain_proto/brain_os/controlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_os.control.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/brain-os/brain_proto/brain_os/control'
  _globals['_EXECUTETRAJECTORYREQUEST']._serialized_start=111
  _globals['_EXECUTETRAJECTORYREQUEST']._serialized_end=188
  _globals['_GRIPPERCONTROLRESPONSE']._serialized_start=190
  _globals['_GRIPPERCONTROLRESPONSE']._serialized_end=303
  _globals['_GETJOINTSTATEREQUEST']._serialized_start=305
  _globals['_GETJOINTSTATEREQUEST']._serialized_end=345
  _globals['_GETJOINTSTATERESPONSE']._serialized_start=347
  _globals['_GETJOINTSTATERESPONSE']._serialized_end=456
  _globals['_EMERGENCYSTOPREQUEST']._serialized_start=458
  _globals['_EMERGENCYSTOPREQUEST']._serialized_end=529
  _globals['_EMERGENCYSTOPRESPONSE']._serialized_start=531
  _globals['_EMERGENCYSTOPRESPONSE']._serialized_end=617
  _globals['_RESUMEMOTIONREQUEST']._serialized_start=619
  _globals['_RESUMEMOTIONREQUEST']._serialized_end=683
  _globals['_RESUMEMOTIONRESPONSE']._serialized_start=685
  _globals['_RESUMEMOTIONRESPONSE']._serialized_end=748
  _globals['_CONTROLSERVICE']._serialized_start=751
  _globals['_CONTROLSERVICE']._serialized_end=1256
# @@protoc_insertion_point(module_scope)
