# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from brain_os.control import service_pb2 as brain__os_dot_control_dot_service__pb2
from brain_os.control import types_pb2 as brain__os_dot_control_dot_types__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in brain_os/control/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub:
    """─────────────────────────────────────────────
    ControlService — 运动控制 gRPC 接口
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTrajectory = channel.unary_stream(
                '/brain_os.control.ControlService/ExecuteTrajectory',
                request_serializer=brain__os_dot_control_dot_service__pb2.ExecuteTrajectoryRequest.SerializeToString,
                response_deserializer=brain__os_dot_control_dot_types__pb2.ExecutionFeedback.FromString,
                _registered_method=True)
        self.ControlGripper = channel.unary_unary(
                '/brain_os.control.ControlService/ControlGripper',
                request_serializer=brain__os_dot_control_dot_types__pb2.GripperCommand.SerializeToString,
                response_deserializer=brain__os_dot_control_dot_service__pb2.GripperControlResponse.FromString,
                _registered_method=True)
        self.GetJointState = channel.unary_unary(
                '/brain_os.control.ControlService/GetJointState',
                request_serializer=brain__os_dot_control_dot_service__pb2.GetJointStateRequest.SerializeToString,
                response_deserializer=brain__os_dot_control_dot_service__pb2.GetJointStateResponse.FromString,
                _registered_method=True)
        self.EmergencyStop = channel.unary_unary(
                '/brain_os.control.ControlService/EmergencyStop',
                request_serializer=brain__os_dot_control_dot_service__pb2.EmergencyStopRequest.SerializeToString,
                response_deserializer=brain__os_dot_control_dot_service__pb2.EmergencyStopResponse.FromString,
                _registered_method=True)
        self.ResumeMotion = channel.unary_unary(
                '/brain_os.control.ControlService/ResumeMotion',
                request_serializer=brain__os_dot_control_dot_service__pb2.ResumeMotionRequest.SerializeToString,
                response_deserializer=brain__os_dot_control_dot_service__pb2.ResumeMotionResponse.FromString,
                _registered_method=True)


class ControlServiceServicer:
    """─────────────────────────────────────────────
    ControlService — 运动控制 gRPC 接口
    ─────────────────────────────────────────────

    """

    def ExecuteTrajectory(self, request, context):
        """执行轨迹（双向流：指令 + 反馈）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlGripper(self, request, context):
        """控制夹爪
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJointState(self, request, context):
        """获取关节状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmergencyStop(self, request, context):
        """紧急停止（最高优先级）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeMotion(self, request, context):
        """恢复运动（紧急停止后）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTrajectory': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteTrajectory,
                    request_deserializer=brain__os_dot_control_dot_service__pb2.ExecuteTrajectoryRequest.FromString,
                    response_serializer=brain__os_dot_control_dot_types__pb2.ExecutionFeedback.SerializeToString,
            ),
            'ControlGripper': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlGripper,
                    request_deserializer=brain__os_dot_control_dot_types__pb2.GripperCommand.FromString,
                    response_serializer=brain__os_dot_control_dot_service__pb2.GripperControlResponse.SerializeToString,
            ),
            'GetJointState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointState,
                    request_deserializer=brain__os_dot_control_dot_service__pb2.GetJointStateRequest.FromString,
                    response_serializer=brain__os_dot_control_dot_service__pb2.GetJointStateResponse.SerializeToString,
            ),
            'EmergencyStop': grpc.unary_unary_rpc_method_handler(
                    servicer.EmergencyStop,
                    request_deserializer=brain__os_dot_control_dot_service__pb2.EmergencyStopRequest.FromString,
                    response_serializer=brain__os_dot_control_dot_service__pb2.EmergencyStopResponse.SerializeToString,
            ),
            'ResumeMotion': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeMotion,
                    request_deserializer=brain__os_dot_control_dot_service__pb2.ResumeMotionRequest.FromString,
                    response_serializer=brain__os_dot_control_dot_service__pb2.ResumeMotionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brain_os.control.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brain_os.control.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService:
    """─────────────────────────────────────────────
    ControlService — 运动控制 gRPC 接口
    ─────────────────────────────────────────────

    """

    @staticmethod
    def ExecuteTrajectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/brain_os.control.ControlService/ExecuteTrajectory',
            brain__os_dot_control_dot_service__pb2.ExecuteTrajectoryRequest.SerializeToString,
            brain__os_dot_control_dot_types__pb2.ExecutionFeedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlGripper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.control.ControlService/ControlGripper',
            brain__os_dot_control_dot_types__pb2.GripperCommand.SerializeToString,
            brain__os_dot_control_dot_service__pb2.GripperControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJointState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.control.ControlService/GetJointState',
            brain__os_dot_control_dot_service__pb2.GetJointStateRequest.SerializeToString,
            brain__os_dot_control_dot_service__pb2.GetJointStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmergencyStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.control.ControlService/EmergencyStop',
            brain__os_dot_control_dot_service__pb2.EmergencyStopRequest.SerializeToString,
            brain__os_dot_control_dot_service__pb2.EmergencyStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeMotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.control.ControlService/ResumeMotion',
            brain__os_dot_control_dot_service__pb2.ResumeMotionRequest.SerializeToString,
            brain__os_dot_control_dot_service__pb2.ResumeMotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
