# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain_os/control/types.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'brain_os/control/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from brain_os.common import types_pb2 as brain__os_dot_common_dot_types__pb2
from brain_os.decision import types_pb2 as brain__os_dot_decision_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x62rain_os/control/types.proto\x12\x10\x62rain_os.control\x1a\x1b\x62rain_os/common/types.proto\x1a\x1d\x62rain_os/decision/types.proto\"w\n\nJointState\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Header\x12\x0c\n\x04name\x18\x02 \x03(\t\x12\x10\n\x08position\x18\x03 \x03(\x01\x12\x10\n\x08velocity\x18\x04 \x03(\x01\x12\x0e\n\x06\x65\x66\x66ort\x18\x05 \x03(\x01\"\xb0\x01\n\x0e\x43ontrolCommand\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x15\n\rtrajectory_id\x18\x02 \x01(\t\x12\x31\n\ntrajectory\x18\x03 \x01(\x0b\x32\x1d.brain_os.decision.Trajectory\x12+\n\x04mode\x18\x04 \x01(\x0e\x32\x1d.brain_os.control.ControlMode\x12\x15\n\renable_safety\x18\x05 \x01(\x08\"\x9d\x02\n\x11\x45xecutionFeedback\x12\'\n\x06header\x18\x01 \x01(\x0b\x32\x17.brain_os.common.Header\x12\x10\n\x08robot_id\x18\x02 \x01(\t\x12\x15\n\rtrajectory_id\x18\x03 \x01(\t\x12\x10\n\x08progress\x18\x04 \x01(\x02\x12\x33\n\rcurrent_state\x18\x05 \x01(\x0b\x32\x1c.brain_os.control.JointState\x12+\n\x0c\x63urrent_pose\x18\x06 \x01(\x0b\x32\x15.brain_os.common.Pose\x12\x16\n\x0etracking_error\x18\x07 \x01(\x02\x12\x13\n\x0bis_complete\x18\x08 \x01(\x08\x12\x15\n\rerror_message\x18\t \x01(\t\"H\n\x0eGripperCommand\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x02\x12\x12\n\nmax_effort\x18\x03 \x01(\x02\"R\n\rGripperStatus\x12\x10\n\x08position\x18\x01 \x01(\x02\x12\x16\n\x0e\x61pplied_effort\x18\x02 \x01(\x02\x12\x17\n\x0fobject_detected\x18\x03 \x01(\x08*U\n\x0b\x43ontrolMode\x12\x11\n\rCTRL_POSITION\x10\x00\x12\x11\n\rCTRL_VELOCITY\x10\x01\x12\x0f\n\x0b\x43TRL_TORQUE\x10\x02\x12\x0f\n\x0b\x43TRL_HYBRID\x10\x03\x42\x32Z0github.com/brain-os/brain_proto/brain_os/controlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_os.control.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/brain-os/brain_proto/brain_os/control'
  _globals['_CONTROLMODE']._serialized_start=856
  _globals['_CONTROLMODE']._serialized_end=941
  _globals['_JOINTSTATE']._serialized_start=110
  _globals['_JOINTSTATE']._serialized_end=229
  _globals['_CONTROLCOMMAND']._serialized_start=232
  _globals['_CONTROLCOMMAND']._serialized_end=408
  _globals['_EXECUTIONFEEDBACK']._serialized_start=411
  _globals['_EXECUTIONFEEDBACK']._serialized_end=696
  _globals['_GRIPPERCOMMAND']._serialized_start=698
  _globals['_GRIPPERCOMMAND']._serialized_end=770
  _globals['_GRIPPERSTATUS']._serialized_start=772
  _globals['_GRIPPERSTATUS']._serialized_end=854
# @@protoc_insertion_point(module_scope)
