# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from brain_os.safety import service_pb2 as brain__os_dot_safety_dot_service__pb2
from brain_os.safety import types_pb2 as brain__os_dot_safety_dot_types__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in brain_os/safety/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SafetyServiceStub:
    """─────────────────────────────────────────────
    SafetyService — 安全监控 gRPC 接口
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSafetySnapshot = channel.unary_unary(
                '/brain_os.safety.SafetyService/GetSafetySnapshot',
                request_serializer=brain__os_dot_safety_dot_service__pb2.GetSafetySnapshotRequest.SerializeToString,
                response_deserializer=brain__os_dot_safety_dot_service__pb2.GetSafetySnapshotResponse.FromString,
                _registered_method=True)
        self.StreamAlarms = channel.unary_stream(
                '/brain_os.safety.SafetyService/StreamAlarms',
                request_serializer=brain__os_dot_safety_dot_service__pb2.StreamAlarmsRequest.SerializeToString,
                response_deserializer=brain__os_dot_safety_dot_types__pb2.SafetyAlarm.FromString,
                _registered_method=True)
        self.AcknowledgeAlarm = channel.unary_unary(
                '/brain_os.safety.SafetyService/AcknowledgeAlarm',
                request_serializer=brain__os_dot_safety_dot_service__pb2.AcknowledgeAlarmRequest.SerializeToString,
                response_deserializer=brain__os_dot_safety_dot_service__pb2.AcknowledgeAlarmResponse.FromString,
                _registered_method=True)
        self.SetVelocityScale = channel.unary_unary(
                '/brain_os.safety.SafetyService/SetVelocityScale',
                request_serializer=brain__os_dot_safety_dot_service__pb2.SetVelocityScaleRequest.SerializeToString,
                response_deserializer=brain__os_dot_safety_dot_service__pb2.SetVelocityScaleResponse.FromString,
                _registered_method=True)


class SafetyServiceServicer:
    """─────────────────────────────────────────────
    SafetyService — 安全监控 gRPC 接口
    ─────────────────────────────────────────────

    """

    def GetSafetySnapshot(self, request, context):
        """获取安全快照
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAlarms(self, request, context):
        """订阅安全告警流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeAlarm(self, request, context):
        """清除已确认告警
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVelocityScale(self, request, context):
        """设置速度缩放因子（安全限速）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SafetyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSafetySnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSafetySnapshot,
                    request_deserializer=brain__os_dot_safety_dot_service__pb2.GetSafetySnapshotRequest.FromString,
                    response_serializer=brain__os_dot_safety_dot_service__pb2.GetSafetySnapshotResponse.SerializeToString,
            ),
            'StreamAlarms': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAlarms,
                    request_deserializer=brain__os_dot_safety_dot_service__pb2.StreamAlarmsRequest.FromString,
                    response_serializer=brain__os_dot_safety_dot_types__pb2.SafetyAlarm.SerializeToString,
            ),
            'AcknowledgeAlarm': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeAlarm,
                    request_deserializer=brain__os_dot_safety_dot_service__pb2.AcknowledgeAlarmRequest.FromString,
                    response_serializer=brain__os_dot_safety_dot_service__pb2.AcknowledgeAlarmResponse.SerializeToString,
            ),
            'SetVelocityScale': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVelocityScale,
                    request_deserializer=brain__os_dot_safety_dot_service__pb2.SetVelocityScaleRequest.FromString,
                    response_serializer=brain__os_dot_safety_dot_service__pb2.SetVelocityScaleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brain_os.safety.SafetyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brain_os.safety.SafetyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SafetyService:
    """─────────────────────────────────────────────
    SafetyService — 安全监控 gRPC 接口
    ─────────────────────────────────────────────

    """

    @staticmethod
    def GetSafetySnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.safety.SafetyService/GetSafetySnapshot',
            brain__os_dot_safety_dot_service__pb2.GetSafetySnapshotRequest.SerializeToString,
            brain__os_dot_safety_dot_service__pb2.GetSafetySnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAlarms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/brain_os.safety.SafetyService/StreamAlarms',
            brain__os_dot_safety_dot_service__pb2.StreamAlarmsRequest.SerializeToString,
            brain__os_dot_safety_dot_types__pb2.SafetyAlarm.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcknowledgeAlarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.safety.SafetyService/AcknowledgeAlarm',
            brain__os_dot_safety_dot_service__pb2.AcknowledgeAlarmRequest.SerializeToString,
            brain__os_dot_safety_dot_service__pb2.AcknowledgeAlarmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVelocityScale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain_os.safety.SafetyService/SetVelocityScale',
            brain__os_dot_safety_dot_service__pb2.SetVelocityScaleRequest.SerializeToString,
            brain__os_dot_safety_dot_service__pb2.SetVelocityScaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
